"""Qt-free helpers for scripts generated by GRIM's Python tab.

The desktop application records semantic dataset and plot operations as ordinary
Python.  This module contains only the small pieces that do not already have a
public :class:`grim_dataset.RcsGrid` method.  It deliberately does not import
PySide6 or pyplot, so a generated script can run on a headless machine with the
Matplotlib Agg canvas.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass
import json
import math
import os
from pathlib import Path
import tempfile
from typing import Callable, Iterable, Sequence
import warnings

import numpy as np

from grim_dataset import RcsGrid


_MAX_EXPLICIT_AXIS_POINTS = 1_000_000


@dataclass(frozen=True)
class DatasetReference:
    """Stable recorder identity plus the best durable source for one GUI row."""

    dataset_id: str
    name: str
    path: str = ""


@dataclass(frozen=True)
class _Code:
    text: str


def _safe_comment(value) -> str:
    """Collapse untrusted display text to one inert Python comment line."""

    text = " ".join(str(value).splitlines())
    return " ".join(text.replace("\x00", " ").split()).strip()


def _compact_numeric_sequence(value) -> str | None:
    """Represent long uniform numeric axes with three hard-coded numbers."""

    try:
        array = np.asarray(value)
    except (TypeError, ValueError):
        return None
    if array.ndim != 1 or array.size < 16 or array.dtype.kind not in "iuf":
        return None
    numeric = np.asarray(array, dtype=np.float64)
    if not np.all(np.isfinite(numeric)):
        return None
    steps = np.diff(numeric)
    if steps.size == 0 or not np.all(steps > 0.0):
        return None
    expected = np.linspace(numeric[0], numeric[-1], numeric.size, dtype=np.float64)
    # The recorder is an exact replay recipe, not a visual approximation.  A
    # tolerance scaled by a large absolute axis can erase a physically real
    # irregular sample.  Compact only if replaying linspace reproduces every
    # float64 value bit-for-bit.
    if not np.array_equal(numeric, expected):
        return None
    return (
        f"np.linspace({_literal(float(numeric[0]))}, "
        f"{_literal(float(numeric[-1]))}, {int(numeric.size)})"
    )


def _literal(value) -> str:
    """Render deterministic Python literals for resolved GUI parameters."""

    if isinstance(value, _Code):
        return value.text
    if isinstance(value, Path):
        return f"Path({_literal(str(value))})"
    if isinstance(value, np.generic):
        return _literal(value.item())
    if isinstance(value, np.ndarray):
        compact = _compact_numeric_sequence(value)
        if compact is not None:
            return compact
        return _literal(value.tolist())
    if isinstance(value, float):
        if math.isnan(value):
            return "float('nan')"
        if math.isinf(value):
            return "float('inf')" if value > 0 else "float('-inf')"
        return repr(value)
    if isinstance(value, tuple):
        body = ", ".join(_literal(item) for item in value)
        if len(value) == 1:
            body += ","
        return f"({body})"
    if isinstance(value, list):
        compact = _compact_numeric_sequence(value)
        if compact is not None:
            return compact
        return "[" + ", ".join(_literal(item) for item in value) + "]"
    if isinstance(value, dict):
        pairs = [f"{_literal(key)}: {_literal(item)}" for key, item in value.items()]
        return "{" + ", ".join(pairs) + "}"
    return repr(value)


def _call_text(callable_text: str, args=(), kwargs=None, *, indent: str = "") -> str:
    kwargs = kwargs or {}
    rendered = [_literal(value) for value in args]
    rendered.extend(f"{key}={_literal(value)}" for key, value in kwargs.items())
    if not rendered:
        return f"{callable_text}()"
    if len(rendered) == 1 and len(rendered[0]) < 72:
        return f"{callable_text}({rendered[0]})"
    continuation = indent + "    "
    return (
        f"{callable_text}(\n"
        + "".join(f"{continuation}{value},\n" for value in rendered)
        + f"{indent})"
    )


class PythonScriptRecorder:
    """Accumulate a readable, dependency-aware Python script.

    Dataset bindings use the immutable ``DATASET_ID_ROLE`` UUID from the GUI,
    never the editable display name.  A row is loaded lazily from its resolved
    path the first time it participates in a recorded operation.
    """

    _HEADER = f'''\
"""Generated by GRIM.  Dataset operations and plot output only."""

import os
from pathlib import Path
import sys

# Set GRIM_MODULE_DIR to the folder containing grim_dataset.py when replaying
# outside the source/install tree used to create this script.
_grim_module_override = os.environ.get("GRIM_MODULE_DIR")
if _grim_module_override:
    _grim_module_candidates = [Path(_grim_module_override).expanduser()]
else:
    _script_dir = Path(__file__).resolve().parent
    _grim_module_candidates = [
        Path({str(Path(__file__).resolve().parent)!r}),
        _script_dir,
        _script_dir / "GRIM_Revised_2",
    ]

GRIM_MODULE_DIR = None
for _candidate in _grim_module_candidates:
    _candidate = _candidate.resolve()
    if (_candidate / "grim_dataset.py").is_file():
        GRIM_MODULE_DIR = _candidate
        if str(_candidate) not in sys.path:
            sys.path.insert(0, str(_candidate))
        break

try:
    import numpy as np

    from grim_dataset import RcsGrid
    from grim_headless import load_dataset
    from grim_python import (
        crop_dataset,
        coherent_divide,
        convert_extrusion,
        duplicate_dataset,
        join_datasets,
        medianize_azimuth,
        offset_db,
        plot_datasets,
        regrid_axis,
        save_dataset_batch,
        shift_dataset,
        stitch_datasets,
        wedge_to_conic,
        wrap_phase,
    )
except ModuleNotFoundError as exc:
    if exc.name in {{"grim_dataset", "grim_headless", "grim_python"}}:
        raise ModuleNotFoundError(
            "GRIM could not be imported. Install the GRIM package, place this "
            "script beside GRIM_Revised_2, or set GRIM_MODULE_DIR to the "
            "folder containing grim_dataset.py."
        ) from exc
    raise
'''

    def __init__(self, on_change: Callable[[str], None] | None = None) -> None:
        self._on_change = on_change
        self._lines: list[str] = []
        self._dataset_vars: dict[str, str] = {}
        self._next_dataset = 1
        self._next_plot = 1
        self._current_plot_var: str | None = None
        self._current_plot_signature: str | None = None
        self._notify()

    @property
    def script(self) -> str:
        body = "\n".join(self._lines)
        if body:
            body = "\n" + body.rstrip() + "\n"
        return self._HEADER + body

    def set_on_change(self, callback: Callable[[str], None] | None) -> None:
        self._on_change = callback
        self._notify()

    def _notify(self) -> None:
        if self._on_change is not None:
            self._on_change(self.script)

    def clear(self) -> None:
        self._lines.clear()
        self._dataset_vars.clear()
        self._next_dataset = 1
        self._next_plot = 1
        self._current_plot_var = None
        self._current_plot_signature = None
        self._notify()

    def _new_dataset_var(self, dataset_id: str) -> str:
        variable = f"dataset_{self._next_dataset}"
        self._next_dataset += 1
        self._dataset_vars[str(dataset_id)] = variable
        return variable

    def bind_loaded(self, reference: DatasetReference) -> str | None:
        existing = self._dataset_vars.get(reference.dataset_id)
        if existing is not None:
            return existing
        if not reference.path:
            return None
        variable = self._new_dataset_var(reference.dataset_id)
        resolved = str(Path(reference.path).expanduser().resolve())
        self._lines.extend(
            [
                f"# Load {_safe_comment(reference.name)}",
                f"{variable} = load_dataset(Path({_literal(resolved)}))",
                "",
            ]
        )
        self._notify()
        return variable

    def _ensure(self, reference: DatasetReference) -> str | None:
        return self._dataset_vars.get(reference.dataset_id) or self.bind_loaded(reference)

    def _skip_unbound(self, operation: str, references: Sequence[DatasetReference]) -> None:
        names = ", ".join(
            _safe_comment(ref.name) for ref in references if not ref.path
        )
        self._lines.extend(
            [
                f"# {_safe_comment(operation)} was not recorded: "
                f"{names or 'an input dataset'} has no replayable source.",
                "# Save that dataset, clear this script, and repeat the operation to capture it.",
                "",
            ]
        )
        self._notify()

    def record_method(
        self,
        output: DatasetReference,
        source: DatasetReference,
        method: str,
        *,
        args=(),
        kwargs=None,
        comment: str = "",
    ) -> str | None:
        source_var = self._ensure(source)
        if source_var is None:
            self._skip_unbound(comment or method, [source])
            return None
        output_var = self._new_dataset_var(output.dataset_id)
        if comment:
            self._lines.append(f"# {_safe_comment(comment)}")
        call = _call_text(f"{source_var}.{method}", args, kwargs)
        self._lines.extend([f"{output_var} = {call}", ""])
        self._notify()
        return output_var

    def record_function(
        self,
        output: DatasetReference,
        function: str,
        sources: Sequence[DatasetReference],
        *,
        args=(),
        kwargs=None,
        comment: str = "",
    ) -> str | None:
        variables = [self._ensure(reference) for reference in sources]
        if any(variable is None for variable in variables):
            self._skip_unbound(comment or function, sources)
            return None
        output_var = self._new_dataset_var(output.dataset_id)
        if comment:
            self._lines.append(f"# {_safe_comment(comment)}")
        call_args = tuple(_Code(str(variable)) for variable in variables) + tuple(args)
        call = _call_text(function, call_args, kwargs)
        self._lines.extend([f"{output_var} = {call}", ""])
        self._notify()
        return output_var

    def record_multi_function(
        self,
        outputs: Sequence[DatasetReference],
        function: str,
        sources: Sequence[DatasetReference],
        *,
        args=(),
        kwargs=None,
        comment: str = "",
    ) -> tuple[str, ...]:
        variables = [self._ensure(reference) for reference in sources]
        if any(variable is None for variable in variables):
            self._skip_unbound(comment or function, sources)
            return ()
        output_vars = tuple(self._new_dataset_var(output.dataset_id) for output in outputs)
        if comment:
            self._lines.append(f"# {_safe_comment(comment)}")
        call_args = tuple(_Code(str(variable)) for variable in variables) + tuple(args)
        call = _call_text(function, call_args, kwargs)
        self._lines.extend([f"{', '.join(output_vars)} = {call}", ""])
        self._notify()
        return output_vars

    def record_expression(
        self,
        output: DatasetReference,
        sources: Sequence[DatasetReference],
        expression: Callable[[tuple[str, ...]], str],
        *,
        comment: str,
    ) -> str | None:
        variables = tuple(self._ensure(reference) for reference in sources)
        if any(variable is None for variable in variables):
            self._skip_unbound(comment, sources)
            return None
        output_var = self._new_dataset_var(output.dataset_id)
        self._lines.extend(
            [
                f"# {_safe_comment(comment)}",
                f"{output_var} = {expression(tuple(str(v) for v in variables))}",
                "",
            ]
        )
        self._notify()
        return output_var

    def record_save(self, reference: DatasetReference, path: str) -> bool:
        variable = self._ensure(reference)
        if variable is None:
            self._skip_unbound("Save dataset", [reference])
            return False
        resolved = str(Path(path).expanduser().resolve())
        self._lines.extend(
            [
                f"# Save {_safe_comment(reference.name)}",
                f"{variable}.save(Path({_literal(resolved)}))",
                "",
            ]
        )
        self._notify()
        return True

    def record_save_batch(
        self,
        entries: Sequence[tuple[DatasetReference, str]],
    ) -> bool:
        """Emit one transactional save call while preserving GUI plan order."""

        if not entries:
            return False
        variables = [self._ensure(reference) for reference, _path in entries]
        if any(variable is None for variable in variables):
            self._skip_unbound(
                "Save dataset batch", [reference for reference, _path in entries]
            )
            return False
        self._lines.extend(
            ["# Transactionally save the dataset batch", "save_dataset_batch(["]
        )
        for variable, (_reference, path) in zip(variables, entries):
            resolved = str(Path(path).expanduser().resolve())
            self._lines.append(
                f"    ({variable}, Path({_literal(resolved)})),"
            )
        self._lines.extend(["])", ""])
        self._notify()
        return True

    def record_plot(
        self,
        datasets: Sequence[DatasetReference],
        *,
        names: Sequence[str],
        mode: str,
        parameters: dict[str, object],
    ) -> str | None:
        supported = {
            "azimuth_rect",
            "azimuth_polar",
            "frequency",
            "elevation_sweep",
            "isar_image",
        }
        mode_key = str(mode).strip().lower()
        if mode_key not in supported:
            self.record_unsupported_plot(
                mode_key,
                "the current headless recorder supports rectangular/polar "
                "azimuth, frequency, elevation-sweep, and ISAR plots only",
            )
            return None
        variables = [self._ensure(reference) for reference in datasets]
        if any(variable is None for variable in variables):
            self._skip_unbound(f"Create {mode} plot", datasets)
            self._current_plot_var = None
            self._current_plot_signature = None
            return None
        signature = _literal(
            (
                tuple(
                    (reference.dataset_id, str(name))
                    for reference, name in zip(datasets, names)
                ),
                mode_key,
                parameters,
            )
        )
        if (
            self._current_plot_var is not None
            and signature == self._current_plot_signature
        ):
            return self._current_plot_var
        variable = f"plot_{self._next_plot}"
        self._next_plot += 1
        named = [
            (str(name), _Code(str(dataset_var)))
            for name, dataset_var in zip(names, variables)
        ]
        kwargs = {"mode": mode_key, **parameters}
        self._lines.append(f"# Create {mode_key.replace('_', ' ')} plot")
        call = _call_text("plot_datasets", (named,), kwargs)
        self._lines.extend([f"{variable} = {call}", ""])
        self._current_plot_var = variable
        self._current_plot_signature = signature
        self._notify()
        return variable

    def record_unsupported_plot(self, mode: str, reason: str) -> None:
        """Explain an omitted plot and prevent export from targeting stale code."""

        signature = _literal(("unsupported", str(mode), str(reason)))
        if self._current_plot_var is None and self._current_plot_signature == signature:
            return
        self._current_plot_var = None
        self._current_plot_signature = signature
        self._lines.extend(
            [
                f"# {_safe_comment(str(mode).replace('_', ' '))} plot was not "
                f"recorded: {_safe_comment(reason)}.",
                "# The plot shown in GRIM can still be exported manually.",
                "",
            ]
        )
        self._notify()

    def invalidate_current_plot(self) -> None:
        """Forget the export target without recording a presentation-only action."""

        self._current_plot_var = None
        self._current_plot_signature = None

    def record_plot_save(self, path: str, *, dpi: int = 200) -> bool:
        if self._current_plot_var is None:
            self._lines.extend(
                [
                    "# Plot export was not recorded: create a recorded plot first.",
                    "",
                ]
            )
            self._notify()
            return False
        resolved = str(Path(path).expanduser().resolve())
        self._lines.extend(
            [
                f"{self._current_plot_var}.savefig(",
                f"    Path({_literal(resolved)}),",
                f"    dpi={int(dpi)},",
                "    bbox_inches='tight',",
                ")",
                "",
            ]
        )
        self._notify()
        return True


def _minimal_physics_extra(dataset: RcsGrid, *, include_phase_reference=True) -> dict:
    extra = {}
    keys = ["time_convention", "polarization_basis"]
    if include_phase_reference:
        keys.insert(0, "phase_reference")
    for key in keys:
        value = dataset._declared_scalar_metadata(key)
        if value:
            extra[key] = value
    return extra


def _derived_response_extra(dataset: RcsGrid) -> dict:
    """Keep response-independent ancillary models, dropping stale grid claims."""

    stale = {
        "amplitude_convention",
        "power_domain",
        "rcs_domain",
        "solver_metadata_json",
        "solver_certification",
        "production_mesh_certification_json",
        "source_body_mesh_certification_json",
        "requested_radar_grid_json",
        "rcs_amp_real",
        "rcs_amp_imag",
    }
    original_shape = tuple(dataset.rcs_power.shape)
    extra = {}
    for key, value in (dataset.extra or {}).items():
        if key in stale:
            continue
        array = np.asarray(value)
        if array.ndim >= 4 and tuple(array.shape[:4]) == original_shape:
            continue
        if isinstance(value, np.ndarray):
            # Response-independent body/geometry models can be much larger
            # than the plotted grid.  A derived dataset does not mutate them,
            # so share storage through a read-only view instead of copying the
            # whole model for every offset or phase edit.
            shared = value.view()
            shared.setflags(write=False)
            extra[key] = shared
        else:
            extra[key] = copy.deepcopy(value)
    return extra


def _copy_grid(
    dataset: RcsGrid,
    *,
    rcs=None,
    rcs_power,
    rcs_phase=None,
    rcs_domain=None,
    units=None,
) -> RcsGrid:
    return RcsGrid(
        dataset.azimuths,
        dataset.elevations,
        dataset.frequencies,
        dataset.polarizations,
        rcs=rcs,
        rcs_power=rcs_power,
        rcs_phase=(
            None
            if rcs is not None
            else dataset.rcs_phase if rcs_phase is None else rcs_phase
        ),
        rcs_domain=rcs_domain or dataset.rcs_domain,
        source_path=dataset.source_path,
        history=dataset.history,
        units=dict(dataset.units or {}) if units is None else dict(units),
        extra=_derived_response_extra(dataset),
    )


def _authoritative_response_phase(dataset: RcsGrid) -> np.ndarray:
    """Return response phase without constructing a whole complex grid.

    Solver-native GRIM files can carry a validated raw real/imaginary pair
    whose phase is authoritative.  ``RcsGrid.rcs`` promotes that pair to a
    full complex128 grid.  Phase-only edits and positive magnitude scaling do
    not need that allocation; ``atan2`` recovers the identical phase directly.
    For ordinary power/phase grids the stored phase is already authoritative
    and can be passed through as a view (the receiving grid owns its copy).
    """

    raw_pair = dataset._complete_authoritative_raw_arrays()
    if raw_pair is None:
        return dataset.rcs_phase
    real, imag = raw_pair
    phase = np.empty(dataset.rcs_power.shape, dtype=np.float64)
    np.arctan2(
        np.asarray(imag, dtype=np.float64),
        np.asarray(real, dtype=np.float64),
        out=phase,
    )
    return phase


def _phase_shifted_response(dataset: RcsGrid, phase_degrees: float) -> np.ndarray:
    """Return authoritative phase shifted into the canonical signed interval."""

    phase = np.array(_authoritative_response_phase(dataset), copy=True)
    delta = np.deg2rad(float(phase_degrees))
    with np.errstate(invalid="ignore"):
        np.add(phase, delta + np.pi, out=phase)
        np.remainder(phase, 2.0 * np.pi, out=phase)
        np.subtract(phase, np.pi, out=phase)
    return phase


def duplicate_dataset(dataset: RcsGrid) -> RcsGrid:
    """Return a detached copy with the same numerical samples and metadata."""

    return RcsGrid(
        dataset.azimuths.copy(),
        dataset.elevations.copy(),
        dataset.frequencies.copy(),
        dataset.polarizations.copy(),
        rcs_power=dataset.rcs_power.copy(),
        rcs_phase=dataset.rcs_phase.copy(),
        rcs_domain=dataset.rcs_domain,
        source_path=dataset.source_path,
        history=dataset.history,
        units=copy.deepcopy(dataset.units or {}),
        extra=copy.deepcopy(dataset.extra or {}),
    )


def _positive_stride(value, name: str) -> int:
    """Validate a replayed physical-axis stride without silently rounding it."""

    if isinstance(value, (bool, np.bool_)) or not isinstance(
        value, (int, np.integer)
    ):
        raise TypeError(f"{name} must be a positive integer")
    stride = int(value)
    if stride <= 0:
        raise ValueError(f"{name} must be a positive integer")
    return stride


def crop_dataset(
    dataset: RcsGrid,
    *,
    azimuths=None,
    elevations=None,
    frequencies=None,
    azimuth_range=None,
    elevation_range=None,
    frequency_range=None,
    azimuth_stride: int = 1,
    elevation_stride: int = 1,
    frequency_stride: int = 1,
    polarizations=None,
) -> RcsGrid:
    """Select values or crop numeric ranges, then retain every Nth sample.

    Ranges and output coordinates use the dataset's native axis units.  The
    helper deliberately delegates both selections to :meth:`RcsGrid.axis_crop`
    so unit metadata, field-convention metadata, history, and source provenance
    follow the same rules as an interactively recorded crop.  A stride is
    sample selection, not an anti-aliasing resample or statistical average.
    """

    strides = {
        "azimuth": _positive_stride(azimuth_stride, "azimuth_stride"),
        "elevation": _positive_stride(elevation_stride, "elevation_stride"),
        "frequency": _positive_stride(frequency_stride, "frequency_stride"),
    }
    ranged = dataset.axis_crop(
        azimuths=azimuths,
        elevations=elevations,
        frequencies=frequencies,
        azimuth_range=azimuth_range,
        elevation_range=elevation_range,
        frequency_range=frequency_range,
        polarizations=polarizations,
    )
    if all(value == 1 for value in strides.values()):
        return ranged
    return ranged.axis_crop(
        azimuths=np.asarray(ranged.azimuths)[:: strides["azimuth"]],
        elevations=np.asarray(ranged.elevations)[:: strides["elevation"]],
        frequencies=np.asarray(ranged.frequencies)[:: strides["frequency"]],
        polarizations=np.asarray(ranged.polarizations),
    )


def regrid_axis(
    dataset: RcsGrid,
    axis: str,
    *,
    start: float | None = None,
    stop: float | None = None,
    step: float | None = None,
    values=None,
) -> RcsGrid:
    """Interpolate one numeric axis onto an explicit, replayable target grid.

    Supply either ``values`` or all of ``start``, ``stop``, and ``step``.
    Values are expressed in the source dataset's native unit and extrapolation
    remains prohibited by :meth:`RcsGrid.interpolate_axis`.  This is the core
    complex/linear interpolation policy; it does not invent an anti-alias
    filter when the requested grid is coarser than the source.
    """

    aliases = {
        "az": "azimuth",
        "azimuths": "azimuth",
        "el": "elevation",
        "elevations": "elevation",
        "freq": "frequency",
        "frequencies": "frequency",
    }
    axis_name = str(axis).strip().lower()
    axis_name = aliases.get(axis_name, axis_name)
    if axis_name not in {"azimuth", "elevation", "frequency"}:
        raise ValueError("axis must be 'azimuth', 'elevation', or 'frequency'")

    bounds_supplied = any(item is not None for item in (start, stop, step))
    if values is not None and bounds_supplied:
        raise ValueError("provide either values or start/stop/step, not both")
    if values is None:
        if any(item is None for item in (start, stop, step)):
            raise ValueError("start, stop, and step are required when values is omitted")
        start_value = float(start)
        stop_value = float(stop)
        step_value = float(step)
        if not all(math.isfinite(item) for item in (start_value, stop_value, step_value)):
            raise ValueError("start, stop, and step must be finite")
        if step_value <= 0.0:
            raise ValueError("step must be positive")
        if stop_value < start_value:
            raise ValueError("stop must be greater than or equal to start")
        count_float = math.floor(
            (stop_value - start_value) / step_value + 1.0e-12
        ) + 1
        if count_float > _MAX_EXPLICIT_AXIS_POINTS:
            raise ValueError(
                f"requested grid has {count_float:,} points; the safety limit is "
                f"{_MAX_EXPLICIT_AXIS_POINTS:,}"
            )
        target = start_value + step_value * np.arange(count_float, dtype=float)
    else:
        target = np.asarray(values, dtype=float).ravel()
        if target.size > _MAX_EXPLICIT_AXIS_POINTS:
            raise ValueError(
                f"requested grid has {target.size:,} points; the safety limit is "
                f"{_MAX_EXPLICIT_AXIS_POINTS:,}"
            )

    if target.size == 0:
        raise ValueError("target grid must contain at least one value")
    if not np.all(np.isfinite(target)):
        raise ValueError("target grid values must be finite")
    if target.size > 1 and np.any(np.diff(target) <= 0.0):
        raise ValueError("target grid values must be strictly increasing")
    return dataset.interpolate_axis(axis_name, target)


def join_datasets(*datasets: RcsGrid, tol: float = 1.0e-6) -> RcsGrid:
    """Join grids with the GUI's conflict and available-memory policies."""

    try:
        import psutil

        available = int(psutil.virtual_memory().available)
    except (ImportError, AttributeError, OSError):
        available = None
    maximum = int(available * 0.5) if available is not None else None
    return RcsGrid.join_many(
        *datasets,
        tol=float(tol),
        overlap="error",
        max_output_bytes=maximum,
    )


def stitch_datasets(
    *datasets: RcsGrid,
    policy: str = "priority-first",
    tol: float = 1.0e-6,
    metadata_attested: bool = False,
    max_output_bytes=None,
    return_report: bool = False,
):
    """Stitch compatible datasets using the core method and its provenance.

    The return value is an :class:`RcsGrid` unless ``return_report`` is true,
    in which case it is the exact ``RcsGrid.stitch_many`` result.
    """

    return RcsGrid.stitch_many(
        *datasets,
        policy=policy,
        tol=float(tol),
        metadata_attested=metadata_attested,
        max_output_bytes=max_output_bytes,
        return_report=return_report,
    )


class DatasetBatchRollbackError(RuntimeError):
    """A batch publication failed and an earlier artifact was not restored."""


def _grim_output_path(path: str | os.PathLike[str]) -> str:
    value = os.fspath(path)
    return value if value.casefold().endswith(".grim") else value + ".grim"


def _replace_file(source: str, destination: str) -> None:
    """Small publication seam kept separate for deterministic rollback tests."""

    os.replace(source, destination)


def save_dataset_batch(
    entries: Sequence[tuple[RcsGrid, str | os.PathLike[str]]],
) -> tuple[Path, ...]:
    """Stage and transactionally publish an ordered batch of GRIM datasets."""

    normalized = [(dataset, _grim_output_path(path)) for dataset, path in entries]
    if not normalized:
        raise ValueError("save_dataset_batch needs at least one dataset and path")
    keys: set[str] = set()
    for _dataset, target in normalized:
        key = os.path.abspath(os.path.normpath(target)).casefold()
        if key in keys:
            raise ValueError(f"multiple datasets resolve to the same output: {target}")
        keys.add(key)

    staged: list[tuple[str, str]] = []
    backups: dict[str, str | None] = {}
    publication_complete = False
    try:
        for dataset, target in normalized:
            if not isinstance(dataset, RcsGrid):
                raise TypeError("save_dataset_batch entries must contain RcsGrid objects")
            absolute_target = os.path.abspath(target)
            directory = os.path.dirname(absolute_target) or os.curdir
            if os.path.lexists(absolute_target) and not os.path.isfile(absolute_target):
                raise OSError(
                    f"output target exists but is not a regular file: {absolute_target}"
                )
            fd, stage_path = tempfile.mkstemp(
                prefix=".grim-stage-",
                suffix=".staging.grim",
                dir=directory,
            )
            os.close(fd)
            try:
                dataset.save(stage_path)
            except Exception:
                try:
                    os.unlink(stage_path)
                except OSError:
                    pass
                raise
            staged.append((stage_path, absolute_target))

        for stage_path, target in staged:
            backup_path: str | None = None
            if os.path.lexists(target):
                directory = os.path.dirname(target) or os.curdir
                fd, backup_path = tempfile.mkstemp(
                    prefix=".grim-backup-",
                    suffix=".backup",
                    dir=directory,
                )
                os.close(fd)
                try:
                    _replace_file(target, backup_path)
                except BaseException:
                    try:
                        os.unlink(backup_path)
                    except OSError:
                        pass
                    raise
            backups[target] = backup_path
            _replace_file(stage_path, target)
        publication_complete = True
    except Exception as original_error:
        rollback_errors: list[str] = []
        for target in reversed(list(backups)):
            backup_path = backups[target]
            try:
                if backup_path and os.path.lexists(backup_path):
                    _replace_file(backup_path, target)
                    backups[target] = None
                elif backup_path is None and os.path.lexists(target):
                    os.unlink(target)
            except OSError as exc:
                rollback_errors.append(f"{target}: {exc}")
        if rollback_errors:
            raise DatasetBatchRollbackError(
                "Dataset publication failed and rollback could not restore every "
                "prior artifact. Retained .grim-backup file(s): "
                + "; ".join(rollback_errors)
            ) from original_error
        raise
    finally:
        for stage_path, _target in staged:
            if os.path.lexists(stage_path):
                try:
                    os.unlink(stage_path)
                except OSError:
                    pass

    if publication_complete:
        for backup_path in backups.values():
            if backup_path and os.path.lexists(backup_path):
                try:
                    os.unlink(backup_path)
                except OSError:
                    pass
    return tuple(Path(target).resolve() for _dataset, target in normalized)


def shift_dataset(
    dataset: RcsGrid,
    *,
    azimuth_degrees: float | None = None,
    elevation_degrees: float | None = None,
    phase_degrees: float | None = None,
) -> RcsGrid:
    """Apply the GUI Shift operation with explicit enabled values."""

    result = dataset
    if azimuth_degrees is not None:
        result = result.shift_azimuth(float(azimuth_degrees))
    if elevation_degrees is not None:
        result = result.shift_elevation(float(elevation_degrees))
    if phase_degrees is not None:
        result = _copy_grid(
            result,
            rcs_power=result.rcs_power,
            rcs_phase=_phase_shifted_response(result, float(phase_degrees)),
            rcs_domain="complex_amplitude",
        )
    return result


def wrap_phase(dataset: RcsGrid, mode: str = "-180_180") -> RcsGrid:
    """Wrap stored phase using the user-facing degree interval names."""

    mode_name = str(mode).strip()
    if mode_name not in {"-180_180", "0_360"}:
        raise ValueError("mode must be '-180_180' or '0_360'")
    return dataset.wrap_phase(mode=mode_name)


def offset_db(dataset: RcsGrid, value_db: float) -> RcsGrid:
    """Shift all displayed RCS values by a constant number of decibels."""

    scale = 10.0 ** (float(value_db) / 10.0)
    return _copy_grid(
        dataset,
        rcs_power=dataset.rcs_power * scale,
        rcs_phase=_authoritative_response_phase(dataset),
        rcs_domain=dataset.rcs_domain,
    )


def coherent_divide(
    numerator: RcsGrid,
    denominator: RcsGrid,
    *,
    metadata_attested: bool = False,
) -> RcsGrid:
    """Complex element-wise division using the GUI's finite/nonzero policy."""

    if not isinstance(metadata_attested, (bool, np.bool_)):
        raise TypeError("metadata_attested must be True or False")
    numerator._assert_compatible(
        denominator,
        coherent=True,
        coherent_metadata_attested=metadata_attested,
        _scan_phase_samples=False,
    )
    shape = tuple(int(value) for value in numerator.rcs_power.shape)
    raw_response = (
        numerator._complete_authoritative_raw_arrays() is not None
        or denominator._complete_authoritative_raw_arrays() is not None
    )
    real_dtype = (
        np.dtype(np.float64)
        if raw_response
        else np.result_type(
            numerator.rcs_power.dtype,
            numerator.rcs_phase.dtype,
            denominator.rcs_power.dtype,
            denominator.rcs_phase.dtype,
        )
    )
    complex_dtype = (
        np.dtype(np.complex128)
        if real_dtype.itemsize > np.dtype(np.float32).itemsize
        else np.dtype(np.complex64)
    )
    result_power = np.full(shape, np.nan, dtype=real_dtype)
    result_phase = np.full(shape, np.nan, dtype=real_dtype)

    # Bound the transient to slices of the leading axis.  A coherent ratio
    # must ultimately own one output grid, but it need not retain both full
    # complex inputs plus a third full complex quotient at the same time.
    cells_per_azimuth = max(1, int(np.prod(shape[1:], dtype=np.int64)))
    working_bytes_per_cell = (
        3 * complex_dtype.itemsize + real_dtype.itemsize + 3
    )
    rows_per_block = max(
        1,
        (16 * 1024**2) // (cells_per_azimuth * working_bytes_per_cell),
    )
    for start in range(0, shape[0], rows_per_block):
        stop = min(shape[0], start + rows_per_block)
        selection = (slice(start, stop), slice(None), slice(None), slice(None))
        left = np.asarray(numerator.rcs_slice(selection), dtype=complex_dtype)
        right = np.asarray(denominator.rcs_slice(selection), dtype=complex_dtype)
        quotient = np.full(left.shape, np.nan + 1j * np.nan, dtype=complex_dtype)
        valid = np.isfinite(left) & np.isfinite(right) & (right != 0)
        np.divide(left, right, out=quotient, where=valid)
        power_block = result_power[selection]
        np.multiply(quotient.real, quotient.real, out=power_block)
        power_block += quotient.imag * quotient.imag
        np.arctan2(
            quotient.imag,
            quotient.real,
            out=result_phase[selection],
        )
        finite_result = np.isfinite(power_block) & np.isfinite(
            result_phase[selection]
        )
        power_block[~finite_result] = np.nan
        result_phase[selection][~finite_result] = np.nan
    usable_count = int(np.count_nonzero(np.isfinite(result_power)))
    if usable_count == 0:
        raise ValueError(
            "coherent division has no common usable complex samples with a "
            "nonzero denominator"
        )
    units = dict(numerator.units or {})
    units["rcs_log_unit"] = "dB"
    units["rcs_linear_quantity"] = "power_ratio"
    # A field ratio is a new dimensionless observable. Do not carry source
    # solver payloads, raw amplitudes, body-model arrays, or certifications
    # that describe the numerator rather than this derived result.
    extra = {}
    for key in ("time_convention", "polarization_basis"):
        left_value = numerator._declared_scalar_metadata(key)
        right_value = denominator._declared_scalar_metadata(key)
        if left_value and right_value:
            extra[key] = left_value
    history, attestation_extra = numerator._coherent_attestation_provenance(
        (denominator,),
        operation="coherent-divide",
        metadata_attested=metadata_attested,
    )
    if history is None:
        history = numerator.history
    if attestation_extra:
        # A field ratio's phase is relative; a source phase-center label does
        # not remain the result's phase reference. The separate attestation
        # record captures compatibility without manufacturing a replacement.
        attestation_extra.pop("phase_reference", None)
        extra.update(attestation_extra)
    extra["coherent_sample_qa_json"] = json.dumps(
        {
            "schema": "grim.coherent-sample-qa.v1",
            "operation": "coherent-divide",
            "total_sample_count": int(result_power.size),
            "usable_sample_count": usable_count,
            "masked_sample_count": int(result_power.size - usable_count),
        },
        sort_keys=True,
        separators=(",", ":"),
    )
    extra["amplitude_convention"] = "complex field ratio"
    return RcsGrid(
        numerator.azimuths,
        numerator.elevations,
        numerator.frequencies,
        numerator.polarizations,
        rcs_power=result_power,
        rcs_phase=result_phase,
        rcs_domain="complex_amplitude",
        source_path=numerator.source_path,
        history=history,
        units=units,
        extra=extra,
    )


def convert_extrusion(dataset: RcsGrid, *, to: str, length_m: float) -> RcsGrid:
    """Convert between sigma_3d/dBsm and sigma_2d/dBke for an extrusion."""

    destination = str(to).strip().lower()
    if destination not in {"dbke", "dbsm"}:
        raise ValueError("to must be 'dbke' or 'dbsm'")
    length = float(length_m)
    if not math.isfinite(length) or length <= 0.0:
        raise ValueError("length_m must be positive and finite")
    source_quantity = str(dataset.linear_quantity()).strip().lower()
    source_log_unit = str(dataset.default_log_unit()).strip().lower()
    if destination == "dbke":
        if source_quantity != "sigma_3d" or source_log_unit != "dbsm":
            raise ValueError(
                "dBsm→dBke requires a sigma_3d/dBsm dataset; "
                f"received {source_quantity or 'unknown'}/{source_log_unit or 'unknown'}"
            )
    elif source_quantity != "sigma_2d" or source_log_unit != "dbke":
        raise ValueError(
            "dBke→dBsm requires a sigma_2d/dBke dataset; "
            f"received {source_quantity or 'unknown'}/{source_log_unit or 'unknown'}"
        )
    frequency_hz = np.asarray(dataset._frequency_value_to_hz(dataset.frequencies), dtype=float)
    c0 = 299_792_458.0
    if destination == "dbke":
        scale = c0 / (2.0 * length * length * frequency_hz)
        quantity = "sigma_2d"
    else:
        scale = 2.0 * length * length * frequency_hz / c0
        quantity = "sigma_3d"
    scale = np.where(np.isfinite(frequency_hz) & (frequency_hz > 0.0), scale, np.nan)
    scale_4d = scale.reshape(1, 1, -1, 1)
    power = dataset.rcs_power * scale_4d
    units = dict(dataset.units or {})
    units["rcs_log_unit"] = "dBke" if destination == "dbke" else "dBsm"
    units["rcs_linear_quantity"] = quantity
    if dataset.rcs_domain == "complex_amplitude":
        rcs = dataset.rcs * np.sqrt(np.maximum(scale_4d, 0.0))
        return RcsGrid(
            dataset.azimuths,
            dataset.elevations,
            dataset.frequencies,
            dataset.polarizations,
            rcs,
            rcs_power=power,
            rcs_domain=dataset.rcs_domain,
            source_path=dataset.source_path,
            history=dataset.history,
            units=units,
            extra=_derived_response_extra(dataset),
        )
    return RcsGrid(
        dataset.azimuths,
        dataset.elevations,
        dataset.frequencies,
        dataset.polarizations,
        rcs=None,
        rcs_power=power,
        rcs_phase=dataset.rcs_phase,
        rcs_domain=dataset.rcs_domain,
        source_path=dataset.source_path,
        history=dataset.history,
        units=units,
        extra=_derived_response_extra(dataset),
    )


def medianize_azimuth(
    dataset: RcsGrid,
    *,
    window_degrees: float,
    slide_degrees: float,
    periodic: bool | None = None,
) -> RcsGrid:
    """Medianize linear power over sliding physical-azimuth windows.

    The public parameters are always degrees. The returned coordinate retains
    the source dataset's native angular unit. A nearly complete 360-degree cut
    is treated as periodic by default, allowing windows to cross its seam.
    """

    window = float(window_degrees)
    slide = float(slide_degrees)
    if not math.isfinite(window) or not math.isfinite(slide) or window <= 0.0 or slide <= 0.0:
        raise ValueError("window_degrees and slide_degrees must be positive and finite")
    unit_raw = str((dataset.units or {}).get("azimuth", "deg")).strip().lower()
    if unit_raw in {"deg", "degree", "degrees"}:
        angle_unit = "deg"
    elif unit_raw in {"rad", "radian", "radians"}:
        angle_unit = "rad"
    else:
        raise ValueError(f"unsupported azimuth unit {unit_raw!r}; use deg or rad")
    native_azimuth = np.asarray(dataset.azimuths, dtype=float)
    azimuth = np.rad2deg(native_azimuth) if angle_unit == "rad" else native_azimuth.copy()
    if azimuth.size < 2:
        raise ValueError("medianize requires at least two azimuth samples")
    if not np.all(np.isfinite(azimuth)) or np.any(np.diff(azimuth) <= 0.0):
        raise ValueError("medianize requires a finite, strictly increasing azimuth axis")

    typical_step = float(np.median(np.diff(azimuth)))
    span = float(azimuth[-1] - azimuth[0])
    if periodic is None:
        periodic = span >= 360.0 - max(1.5 * typical_step, 1.0e-6)
    periodic = bool(periodic)
    if periodic and window > 360.0 + 1.0e-9:
        raise ValueError("a periodic median window cannot exceed 360 degrees")

    half = window * 0.5
    sample_azimuth = azimuth
    merged_seam_power = None
    if periodic and np.isclose(span, 360.0, rtol=0.0, atol=1.0e-7):
        # A closed sweep often stores both endpoints (0/360 or -180/180).
        # They are one physical direction and must carry one statistical
        # weight.  Merge complementary sparse data and reject genuinely
        # inconsistent finite endpoint samples before dropping the duplicate.
        merged_seam_power = np.array(dataset.rcs_power[0], copy=True)
        merged_seam_phase = np.array(dataset.rcs_phase[0], copy=True)
        RcsGrid._merge_equivalent_sample_blocks(
            merged_seam_power,
            merged_seam_phase,
            dataset.rcs_power[-1],
            dataset.rcs_phase[-1],
            context="medianize periodic endpoint",
        )
        sample_azimuth = azimuth[:-1]
    if periodic:
        count_float = np.ceil(360.0 / slide - 1.0e-12)
        if count_float > _MAX_EXPLICIT_AXIS_POINTS:
            raise ValueError(
                f"medianize would create {int(count_float):,} azimuths; "
                f"the safety limit is {_MAX_EXPLICIT_AXIS_POINTS:,}"
            )
        centers = float(azimuth[0]) + np.arange(int(count_float), dtype=float) * slide
        centers = centers[centers < float(azimuth[0]) + 360.0 - 1.0e-10]
        source_indices = np.arange(sample_azimuth.size, dtype=np.int64)
        augmented_azimuth = np.concatenate(
            (sample_azimuth - 360.0, sample_azimuth, sample_azimuth + 360.0)
        )
        augmented_indices = np.tile(source_indices, 3)
    else:
        first = float(azimuth[0]) + half
        last = float(azimuth[-1]) - half
        if last < first:
            centers = np.asarray([(float(azimuth[0]) + float(azimuth[-1])) * 0.5])
        else:
            count_float = np.floor((last - first) / slide + 1e-9) + 1.0
            if count_float > _MAX_EXPLICIT_AXIS_POINTS:
                raise ValueError(
                    f"medianize would create {int(count_float):,} azimuths; "
                    f"the safety limit is {_MAX_EXPLICIT_AXIS_POINTS:,}"
                )
            centers = first + np.arange(int(count_float), dtype=float) * slide
    shape = (centers.size,) + dataset.rcs_power.shape[1:]
    power = np.empty(shape, dtype=dataset.rcs_power.dtype)
    for index, center in enumerate(centers):
        if periodic:
            left = int(np.searchsorted(augmented_azimuth, center - half, side="left"))
            right = int(np.searchsorted(augmented_azimuth, center + half, side="right"))
            samples = np.unique(augmented_indices[left:right])
        else:
            left = int(np.searchsorted(azimuth, center - half, side="left"))
            right = int(np.searchsorted(azimuth, center + half, side="right"))
            samples = np.arange(left, right, dtype=np.int64)
        if samples.size == 0:
            if periodic:
                distance = np.abs(
                    (sample_azimuth - center + 180.0) % 360.0 - 180.0
                )
            else:
                distance = np.abs(azimuth - center)
            samples = np.asarray([int(np.argmin(distance))])
        sample_power = dataset.rcs_power[samples]
        if merged_seam_power is not None and np.any(samples == 0):
            # Advanced indexing above owns this compact window, so replacing
            # its seam row cannot mutate the source dataset.
            sample_power[np.flatnonzero(samples == 0)] = merged_seam_power
        power[index] = np.nanmedian(sample_power, axis=0)
    output_centers = np.deg2rad(centers) if angle_unit == "rad" else centers
    extra = {}
    for key in ("time_convention", "polarization_basis"):
        value = dataset._declared_scalar_metadata(key)
        if value:
            extra[key] = value
    extra["amplitude_convention"] = (
        "sliding median of linear power; coherent phase is undefined"
    )
    return RcsGrid(
        output_centers,
        dataset.elevations,
        dataset.frequencies,
        dataset.polarizations,
        rcs=None,
        rcs_power=power,
        rcs_phase=np.full_like(power, np.nan),
        rcs_domain=dataset.rcs_domain,
        source_path=dataset.source_path,
        history=dataset.history,
        units=dict(dataset.units or {}),
        extra=extra,
    )


def wedge_to_conic(
    dataset: RcsGrid,
    *,
    mode: str = "regrid",
    assume_missing_cross_pol_zero: bool = False,
) -> RcsGrid:
    """Replay the GUI's physical wedge-to-normal-conic conversion."""

    mode_key = str(mode).strip().lower()
    if mode_key == "relabel":
        raise ValueError(
            "Wedge relabel is not physically representable as a rectangular "
            "RcsGrid; use mode='regrid'."
        )
    if mode_key != "regrid":
        raise ValueError("mode must be 'regrid'")
    return dataset.convert_wedge_to_conic(
        attest_wedge_axes=False,
        assume_missing_cross_pol_zero=assume_missing_cross_pol_zero,
    )


def _indices(axis, selected, *, text=False, tolerance=1.0e-6) -> list[int]:
    values = np.asarray(axis)
    result: list[int] = []
    for requested in selected:
        if text:
            matches = np.flatnonzero(values.astype(str) == str(requested))
        else:
            matches = np.flatnonzero(
                np.isclose(values.astype(float), float(requested), atol=tolerance, rtol=0.0)
            )
        if matches.size != 1:
            raise ValueError(f"Selected value {requested!r} is missing or ambiguous")
        result.append(int(matches[0]))
    return result


def _display_values(dataset: RcsGrid, values, *, frequency, phase: bool, scale: str):
    if phase:
        phase_degrees = np.rad2deg(np.angle(values))
        finite = np.isfinite(phase_degrees)
        display = np.full(np.asarray(phase_degrees).shape, np.nan, dtype=float)
        phase_wrap = str(
            (dataset.units or {}).get("phase_wrap", "-180_180")
        ).strip()
        if phase_wrap == "0_360":
            display[finite] = np.mod(phase_degrees[finite], 360.0)
        else:
            display[finite] = (
                np.mod(phase_degrees[finite] + 180.0, 360.0) - 180.0
            )
        return display
    if str(scale).lower() == "linear":
        return dataset.rcs_to_linear(values)
    return dataset.rcs_to_display_db(values, frequency_value=frequency)


def _plot_selection_indices(
    reference: RcsGrid,
    dataset: RcsGrid,
    azimuths,
    elevations,
    frequencies,
    polarization,
):
    """Return converted requested indices, or ``None`` like the GUI policy."""

    from plot_modes import common as plot_common

    try:
        native_azimuths, azimuth_tolerance = plot_common.selection_for_dataset(
            reference, dataset, "azimuth", azimuths
        )
        native_elevations, elevation_tolerance = plot_common.selection_for_dataset(
            reference, dataset, "elevation", elevations
        )
        native_frequencies, frequency_tolerance = plot_common.selection_for_dataset(
            reference, dataset, "frequency", frequencies
        )
        return (
            _indices(
                dataset.azimuths,
                native_azimuths,
                tolerance=azimuth_tolerance,
            ),
            _indices(
                dataset.elevations,
                native_elevations,
                tolerance=elevation_tolerance,
            ),
            _indices(
                dataset.frequencies,
                native_frequencies,
                tolerance=frequency_tolerance,
            ),
            _indices(dataset.polarizations, [polarization], text=True)[0],
        )
    except (TypeError, ValueError):
        return None


def _plot_response_label(
    reference: RcsGrid,
    *,
    phase: bool,
    scale: str,
    p50: bool = False,
) -> str:
    """Match the GUI's response-quantity labels in generated plots."""

    if phase:
        return "Phase P50 (deg)" if p50 else "Phase (deg)"
    quantity_name, linear_unit = {
        "sigma_3d": ("RCS", "m²"),
        "sigma_2d": ("Scattering Width", "m"),
        "power_ratio": ("Power Ratio", "dimensionless"),
        "ratio": ("Power Ratio", "dimensionless"),
    }.get(str(reference.linear_quantity()).strip().lower(), ("Value", "linear"))
    suffix = " P50" if p50 else ""
    if str(scale).strip().lower() == "linear":
        return f"{quantity_name}{suffix} ({linear_unit})"
    return f"{quantity_name}{suffix} ({reference.default_log_unit()})"


def plot_datasets(
    datasets: Sequence[tuple[str, RcsGrid]],
    *,
    mode: str,
    azimuths: Iterable[float],
    elevations: Iterable[float],
    frequencies: Iterable[float],
    polarization: str,
    phase: bool = False,
    scale: str = "dbsm",
    colormap: str = "viridis",
    show_grid: bool = True,
    show_legend: bool = True,
    polar_zero: str = "N",
    reference_index: int = 0,
    waterfall_style: str = "Surface",
    isar_options: dict[str, object] | None = None,
    show_colorbar: bool = True,
    shared_colorbar: bool = True,
    square_aspect: bool = False,
    color_limits: tuple[float, float] | None = None,
    color_step: float = 0.0,
):
    """Create a Matplotlib Figure from resolved physical selector values.

    The implementation uses :class:`~matplotlib.backends.backend_agg.FigureCanvasAgg`
    directly and never imports pyplot or Qt.  Returned figures support ordinary
    ``figure.savefig(...)`` calls in generated scripts.
    """

    from matplotlib.backends.backend_agg import FigureCanvasAgg
    from matplotlib.figure import Figure

    selected = [(str(name), grid) for name, grid in datasets]
    if not selected:
        raise ValueError("plot_datasets needs at least one dataset")
    mode_key = str(mode).strip().lower()
    supported_modes = {
        "azimuth_rect",
        "azimuth_polar",
        "frequency",
        "elevation_sweep",
        "isar_image",
    }
    if mode_key not in supported_modes:
        raise ValueError(
            f"Unsupported headless plot mode {mode!r}; supported modes are "
            "azimuth_rect, azimuth_polar, frequency, elevation_sweep, and "
            "isar_image"
        )
    if mode_key == "isar_image" and len(selected) != 1:
        raise ValueError("ISAR headless plotting requires exactly one dataset")
    try:
        reference_position = int(reference_index)
    except (TypeError, ValueError) as exc:
        raise ValueError("reference_index must identify one selected dataset") from exc
    if reference_position < 0 or reference_position >= len(selected):
        raise ValueError("reference_index must identify one selected dataset")
    reference = selected[reference_position][1]

    from plot_modes import common as plot_common

    plot_common.validate_plot_datasets(
        selected,
        phase=bool(phase),
        linear=str(scale).strip().lower() == "linear",
    )
    az_values = [float(value) for value in azimuths]
    el_values = [float(value) for value in elevations]
    freq_values = [float(value) for value in frequencies]
    if not az_values or not el_values or not freq_values:
        raise ValueError("azimuths, elevations, and frequencies cannot be empty")
    compatible_count = 0
    style_axes = None

    figure = Figure(figsize=(10.0, 6.0), dpi=100, facecolor="white")
    FigureCanvasAgg(figure)
    if mode_key == "azimuth_polar":
        axes = figure.add_subplot(111, projection="polar")
        axes.set_theta_zero_location(str(polar_zero))
        axes.set_theta_direction(-1)
    elif mode_key == "compare":
        axes, residual_axes = figure.subplots(
            2, 1, sharex=True, gridspec_kw={"height_ratios": [3, 1]}
        )
    elif mode_key == "waterfall":
        axes = figure.add_subplot(111, projection="3d")
    else:
        axes = figure.add_subplot(111)

    if mode_key in {"azimuth_rect", "azimuth_polar"}:
        for name, dataset in selected:
            indices = _plot_selection_indices(
                reference,
                dataset,
                az_values,
                el_values,
                freq_values,
                polarization,
            )
            if indices is None:
                continue
            az_idx, el_idx, fr_idx, pol_idx = indices
            compatible_count += 1
            native_x = np.asarray(dataset.azimuths)[az_idx]
            x = plot_common.values_for_display(
                reference, dataset, "azimuth", native_x
            )
            order = np.argsort(x)
            x = np.asarray(x)[order]
            if mode_key == "azimuth_polar":
                x = plot_common.convert_axis_values(
                    x,
                    "azimuth",
                    plot_common.axis_unit(reference, "azimuth"),
                    "rad",
                )
            for fi in fr_idx:
                for ei in el_idx:
                    selection = np.ix_(az_idx, [ei], [fi], [pol_idx])
                    raw = (
                        dataset.rcs_slice(selection)[:, 0, 0, 0]
                        if phase
                        else dataset.rcs_power[np.ix_(az_idx, [ei], [fi], [pol_idx])][:, 0, 0, 0]
                    )
                    y = _display_values(
                        dataset,
                        raw,
                        frequency=float(dataset.frequencies[fi]),
                        phase=phase,
                        scale=scale,
                    )[order]
                    axes.plot(
                        x,
                        y,
                        label=(
                            f"{name} | {polarization}, "
                            f"{float(plot_common.values_for_display(reference, dataset, 'frequency', [dataset.frequencies[fi]])[0]):g} "
                            f"{plot_common.axis_unit(reference, 'frequency')}, "
                            f"{plot_common.angular_axis_name(reference, 'elevation')} "
                            f"{float(plot_common.values_for_display(reference, dataset, 'elevation', [dataset.elevations[ei]])[0]):g} "
                            f"{plot_common.axis_unit(reference, 'elevation')}"
                        ),
                    )
        axes.set_xlabel(plot_common.axis_label(reference, "azimuth"))
        axes.set_ylabel(
            _plot_response_label(reference, phase=phase, scale=scale)
        )

    elif mode_key == "frequency":
        for name, dataset in selected:
            indices = _plot_selection_indices(
                reference,
                dataset,
                az_values,
                el_values,
                freq_values,
                polarization,
            )
            if indices is None:
                continue
            az_idx, el_idx, fr_idx, pol_idx = indices
            compatible_count += 1
            native_x = np.asarray(dataset.frequencies)[fr_idx]
            x = plot_common.values_for_display(
                reference, dataset, "frequency", native_x
            )
            order = np.argsort(x)
            for ei in el_idx:
                if phase:
                    block = dataset.rcs_slice(
                        np.ix_(az_idx, [ei], fr_idx, [pol_idx])
                    )[:, 0, :, 0]
                    phase_degrees = np.rad2deg(np.angle(block))
                    phase_degrees = np.where(np.isfinite(block), phase_degrees, np.nan)
                    y = plot_common.circular_median_degrees(
                        phase_degrees, axis=0
                    )
                else:
                    block = dataset.rcs_power[np.ix_(az_idx, [ei], fr_idx, [pol_idx])][:, 0, :, 0]
                    power = np.nanmedian(block, axis=0)
                    y = _display_values(
                        dataset,
                        power,
                        frequency=native_x,
                        phase=False,
                        scale=scale,
                    )
                elevation = float(
                    plot_common.values_for_display(
                        reference,
                        dataset,
                        "elevation",
                        [dataset.elevations[ei]],
                    )[0]
                )
                axes.plot(
                    np.asarray(x)[order],
                    np.asarray(y)[order],
                    label=(
                        f"{name} | "
                        f"{plot_common.angular_axis_name(reference, 'elevation')} "
                        f"{elevation:g} {plot_common.axis_unit(reference, 'elevation')}"
                    ),
                )
        axes.set_xlabel(plot_common.axis_label(reference, "frequency"))
        axes.set_ylabel(
            _plot_response_label(reference, phase=phase, scale=scale, p50=True)
        )

    elif mode_key == "elevation_sweep":
        for name, dataset in selected:
            indices = _plot_selection_indices(
                reference,
                dataset,
                az_values,
                el_values,
                freq_values,
                polarization,
            )
            if indices is None:
                continue
            az_idx, el_idx, fr_idx, pol_idx = indices
            compatible_count += 1
            native_x = np.asarray(dataset.elevations)[el_idx]
            x = plot_common.values_for_display(
                reference, dataset, "elevation", native_x
            )
            order = np.argsort(x)
            for fi in fr_idx:
                if phase:
                    block = dataset.rcs_slice(
                        np.ix_(az_idx, el_idx, [fi], [pol_idx])
                    )[:, :, 0, 0]
                    phase_degrees = np.rad2deg(np.angle(block))
                    phase_degrees = np.where(np.isfinite(block), phase_degrees, np.nan)
                    y = (
                        plot_common.circular_median_degrees(
                            phase_degrees, axis=0
                        )
                        if len(az_idx) > 1
                        else phase_degrees[0]
                    )
                else:
                    block = dataset.rcs_power[np.ix_(az_idx, el_idx, [fi], [pol_idx])][:, :, 0, 0]
                    power = np.nanmedian(block, axis=0) if len(az_idx) > 1 else block[0]
                    y = _display_values(dataset, power, frequency=dataset.frequencies[fi], phase=False, scale=scale)
                frequency = float(
                    plot_common.values_for_display(
                        reference,
                        dataset,
                        "frequency",
                        [dataset.frequencies[fi]],
                    )[0]
                )
                axes.plot(
                    np.asarray(x)[order],
                    np.asarray(y)[order],
                    label=(
                        f"{name} | {frequency:g} "
                        f"{plot_common.axis_unit(reference, 'frequency')}"
                    ),
                )
        axes.set_xlabel(plot_common.axis_label(reference, "elevation"))
        axes.set_ylabel(
            _plot_response_label(
                reference,
                phase=phase,
                scale=scale,
                p50=len(az_values) > 1,
            )
        )

    elif mode_key == "compare":
        if len(selected) != 2:
            raise ValueError("compare requires exactly two datasets")
        varying = "azimuth" if len(az_values) > 1 else "elevation" if len(el_values) > 1 else "frequency"
        series_values = []
        for name, dataset in selected:
            az_idx = _indices(dataset.azimuths, az_values)
            el_idx = _indices(dataset.elevations, el_values)
            fr_idx = _indices(dataset.frequencies, freq_values)
            pol_idx = _indices(dataset.polarizations, [polarization], text=True)[0]
            if varying == "azimuth":
                x = np.asarray(dataset.azimuths)[az_idx]
                selection = np.ix_(az_idx, [el_idx[0]], [fr_idx[0]], [pol_idx])
                raw = (
                    dataset.rcs_slice(selection)
                    if phase
                    else dataset.rcs_power[selection]
                )[:, 0, 0, 0]
                frequency = dataset.frequencies[fr_idx[0]]
            elif varying == "elevation":
                x = np.asarray(dataset.elevations)[el_idx]
                selection = np.ix_([az_idx[0]], el_idx, [fr_idx[0]], [pol_idx])
                raw = (
                    dataset.rcs_slice(selection)
                    if phase
                    else dataset.rcs_power[selection]
                )[0, :, 0, 0]
                frequency = dataset.frequencies[fr_idx[0]]
            else:
                x = np.asarray(dataset.frequencies)[fr_idx]
                selection = np.ix_([az_idx[0]], [el_idx[0]], fr_idx, [pol_idx])
                raw = (
                    dataset.rcs_slice(selection)
                    if phase
                    else dataset.rcs_power[selection]
                )[0, 0, :, 0]
                frequency = x
            y = _display_values(dataset, raw, frequency=frequency, phase=phase, scale=scale)
            order = np.argsort(x)
            x, y = np.asarray(x)[order], np.asarray(y)[order]
            axes.plot(x, y, label=name)
            series_values.append((x, y))
        common, left_idx, right_idx = np.intersect1d(
            np.round(series_values[0][0], 8),
            np.round(series_values[1][0], 8),
            return_indices=True,
        )
        if common.size:
            residual_axes.plot(common, series_values[0][1][left_idx] - series_values[1][1][right_idx])
        residual_axes.axhline(0.0, color="gray", linestyle="--")
        residual_axes.set_xlabel(varying.title())
        residual_axes.set_ylabel("Residual")
        axes.set_ylabel("Phase (deg)" if phase else ("RCS (Linear)" if scale == "linear" else "RCS (dB)"))

    elif mode_key == "waterfall":
        for name, dataset in selected:
            az_idx = _indices(dataset.azimuths, az_values)
            el_idx = _indices(dataset.elevations, el_values)
            fr_idx = _indices(dataset.frequencies, freq_values)
            pol_idx = _indices(dataset.polarizations, [polarization], text=True)[0]
            az_axis = np.asarray(dataset.azimuths)[az_idx]
            fr_axis = np.asarray(dataset.frequencies)[fr_idx]
            x_mesh, y_mesh = np.meshgrid(az_axis, fr_axis, indexing="ij")
            for ei in el_idx:
                selection = np.ix_(az_idx, [ei], fr_idx, [pol_idx])
                raw = (
                    dataset.rcs_slice(selection)
                    if phase
                    else dataset.rcs_power[selection]
                )[:, 0, :, 0]
                z = _display_values(dataset, raw, frequency=fr_axis[None, :], phase=phase, scale=scale)
                if str(waterfall_style).lower().startswith("wire"):
                    axes.plot_wireframe(x_mesh, y_mesh, z, label=name)
                else:
                    axes.plot_surface(x_mesh, y_mesh, z, cmap=colormap, alpha=0.85)
        axes.set_xlabel("Azimuth (deg)")
        axes.set_ylabel(f"Frequency ({selected[0][1].units.get('frequency', 'GHz')})")
        axes.set_zlabel("Phase (deg)" if phase else ("RCS (Linear)" if scale == "linear" else "RCS (dB)"))

    elif mode_key == "az_vs_range":
        dataset = selected[0][1]
        name = selected[0][0]
        az_idx = _indices(dataset.azimuths, az_values)
        fr_idx = _indices(dataset.frequencies, freq_values)
        el_idx = _indices(dataset.elevations, [el_values[0]])[0]
        pol_idx = _indices(dataset.polarizations, [polarization], text=True)[0]
        freq = np.asarray(dataset._frequency_value_to_hz(dataset.frequencies[fr_idx]), dtype=float)
        order_f = np.argsort(freq)
        freq = freq[order_f]
        complex_data = dataset.rcs_slice(
            np.ix_(az_idx, [el_idx], fr_idx, [pol_idx])
        )[:, 0, :, 0][:, order_f]
        window = np.hanning(freq.size)
        image = np.fft.fftshift(np.fft.ifft(complex_data * window[None, :], axis=1), axes=1)
        distance = np.fft.fftshift(np.fft.fftfreq(freq.size, d=float(np.mean(np.diff(freq))))) * 299_792_458.0 / 2.0
        magnitude = np.abs(image)
        display = magnitude if scale == "linear" else 20.0 * np.log10(np.maximum(magnitude, 1.0e-15))
        axes.pcolormesh(np.asarray(dataset.azimuths)[az_idx], distance, display.T, shading="auto", cmap=colormap)
        axes.set_title(name)
        axes.set_xlabel("Azimuth (deg)")
        axes.set_ylabel("Down-Range (m)")

    elif mode_key == "isar_image":
        from plot_modes.isar_mode import _length_unit, form_isar

        dataset = selected[0][1]
        options = dict(isar_options or {})
        # This helper produces a rendered plot, not a scientific result
        # artifact. Formation remains full fidelity, then the same
        # peak-preserving display reduction as the GUI bounds image/log
        # temporaries. Complex images are intentionally not retained here.
        options["decimate_display"] = True
        options["retain_complex"] = False
        az_idx = _indices(dataset.azimuths, az_values)
        fr_idx = _indices(dataset.frequencies, freq_values)
        el_idx = _indices(dataset.elevations, [el_values[0]])[0]
        pol_idx = _indices(dataset.polarizations, [polarization], text=True)[0]
        bands, _elapsed = form_isar(
            dataset,
            azimuth_indices=az_idx,
            frequency_indices=fr_idx,
            elevation_index=el_idx,
            polarization_index=pol_idx,
            **options,
        )
        compatible_count = 1
        figure.clear()
        axes_values = figure.subplots(1, len(bands), squeeze=False)[0]
        style_axes = list(axes_values)
        displays = []
        for band in bands:
            magnitude = np.asarray(band["magnitude"], dtype=np.float32)
            intensity = np.empty_like(magnitude, dtype=np.float32)
            np.multiply(magnitude, magnitude, out=intensity)
            if str(scale).strip().lower() != "linear":
                # Match the GUI's defined display floor exactly: image
                # intensity at/below 1e-12 is shown as -120 dB.
                np.maximum(intensity, np.float32(1.0e-12), out=intensity)
                np.log10(intensity, out=intensity)
                intensity *= np.float32(10.0)
            displays.append(intensity)

        clamp = None
        if color_limits is not None:
            values = np.asarray(color_limits, dtype=float).reshape(-1)
            if (
                values.size != 2
                or not np.all(np.isfinite(values))
                or not values[0] < values[1]
            ):
                raise ValueError("color_limits must be two finite increasing values")
            clamp = (float(values[0]), float(values[1]))
        shared_limits = (
            plot_common.finite_data_limits(displays)
            if bool(shared_colorbar) and clamp is None
            else None
        )
        plot_vmin = clamp[0] if clamp is not None else (
            shared_limits[0] if shared_limits is not None else None
        )
        plot_vmax = clamp[1] if clamp is not None else (
            shared_limits[1] if shared_limits is not None else None
        )

        meshes = []
        for axis, band, display in zip(axes_values, bands, displays):
            mesh = axis.imshow(
                display.T,
                extent=[band["x_range"][0], band["x_range"][-1], band["y_range"][0], band["y_range"][-1]],
                origin="lower",
                aspect="auto",
                interpolation="nearest",
                cmap=colormap,
                vmin=plot_vmin,
                vmax=plot_vmax,
            )
            if bool(square_aspect):
                axis.set_aspect("equal", adjustable="datalim")
            meshes.append(mesh)

        unit_name, _unit_scale = _length_unit(options.get("length_unit", "m"))
        elevation_native = float(np.asarray(dataset.elevations)[el_idx])
        elevation_deg = float(
            plot_common.convert_axis_values(
                [elevation_native],
                "elevation",
                plot_common.axis_unit(dataset, "elevation"),
                "deg",
            )[0]
        )
        elevation_name = plot_common.angular_axis_name(dataset, "elevation")
        reconstruction = str(options.get("reconstruction", "fast")).strip().lower()
        if reconstruction in {"sparse", "l1", "sparse-l1"}:
            reconstruction_label = "Sparse L1 (Experimental)"
        elif reconstruction in {"accurate", "cartesian", "pfa-accurate"}:
            reconstruction_label = "Cartesian PFA"
        else:
            reconstruction_label = "Fast PFA"
        composite_sublooks = max(
            (int(band.get("composite", 0)) for band in bands), default=0
        )
        if composite_sublooks:
            reconstruction_label += (
                f" | Wide-Aperture Composite ({composite_sublooks} looks)"
            )
        title = (
            f"ISAR Image | {elevation_name} {elevation_deg:g} deg | "
            f"Pol {dataset.polarizations[pol_idx]} | {reconstruction_label}"
        )
        if len(bands) > 1:
            figure.suptitle(title)
            for axis, band in zip(axes_values, bands):
                axis.set_title(
                    f"{float(band['az_values'][0]):g}°–"
                    f"{float(band['az_values'][-1]):g}°"
                )
        else:
            axes_values[0].set_title(title)

        horizontal_projection = abs(elevation_deg) > 1.0e-9
        if composite_sublooks:
            x_label = f"Cross-Range at 0° ({unit_name})"
            y_label = f"Down-Range at 0° ({unit_name})"
        elif horizontal_projection:
            x_label = f"Horizontal Cross-Range ({unit_name})"
            y_label = f"Horizontal Range ({unit_name})"
        else:
            x_label = f"Cross-Range ({unit_name})"
            y_label = f"Range ({unit_name})"
        for axis in axes_values:
            axis.set_xlabel(x_label)
        axes_values[0].set_ylabel(y_label)

        colorbars = []
        if bool(show_colorbar) and meshes:
            if bool(shared_colorbar):
                colorbars.append(figure.colorbar(meshes[-1], ax=list(axes_values)))
            else:
                colorbars.extend(
                    figure.colorbar(mesh, ax=axis)
                    for axis, mesh in zip(axes_values, meshes)
                )
            label = (
                "Image Intensity (linear)"
                if str(scale).strip().lower() == "linear"
                else "Image Intensity (dB)"
            )
            try:
                tick_step = float(color_step)
            except (TypeError, ValueError) as exc:
                raise ValueError("color_step must be finite and nonnegative") from exc
            if not np.isfinite(tick_step) or tick_step < 0.0:
                raise ValueError("color_step must be finite and nonnegative")
            for colorbar in colorbars:
                colorbar.set_label(label)
                if tick_step > 0.0:
                    low, high = colorbar.mappable.get_clim()
                    first = math.ceil(low / tick_step) * tick_step
                    tick_count = int(math.floor((high - first) / tick_step)) + 1
                    if 0 < tick_count <= 1000:
                        colorbar.set_ticks(first + tick_step * np.arange(tick_count))

        sparse_results = [
            band for band in bands if band.get("sparse_iterations") is not None
        ]
        if sparse_results and not all(
            bool(band.get("sparse_converged", False)) for band in sparse_results
        ):
            worst_gap = max(
                float(band.get("sparse_relative_duality_gap", float("inf")))
                for band in sparse_results
            )
            warnings.warn(
                "ISAR sparse reconstruction did not certify convergence for "
                f"every band (worst relative duality gap {worst_gap:.3g}); "
                "treat the image as diagnostic, not quantitatively final.",
                RuntimeWarning,
                stacklevel=2,
            )
        axes = axes_values[0]
    else:
        raise ValueError(f"Unsupported plot mode: {mode!r}")

    if compatible_count == 0:
        figure.clear()
        raise ValueError(
            "None of the selected datasets contains every requested plot axis value"
        )

    for axis in (style_axes if style_axes is not None else figure.axes):
        axis.grid(bool(show_grid))
        handles, labels = axis.get_legend_handles_labels()
        if show_legend and handles:
            axis.legend()
    figure.tight_layout()
    return figure


__all__ = [
    "DatasetBatchRollbackError",
    "DatasetReference",
    "PythonScriptRecorder",
    "coherent_divide",
    "convert_extrusion",
    "crop_dataset",
    "duplicate_dataset",
    "join_datasets",
    "medianize_azimuth",
    "offset_db",
    "plot_datasets",
    "regrid_axis",
    "save_dataset_batch",
    "shift_dataset",
    "stitch_datasets",
    "wedge_to_conic",
    "wrap_phase",
]
