"""Qt-free helpers for scripts generated by GRIM's Python tab.

The desktop application records semantic dataset and plot operations as ordinary
Python.  This module contains only the small pieces that do not already have a
public :class:`grim_dataset.RcsGrid` method.  It deliberately does not import
PySide6 or pyplot, so a generated script can run on a headless machine with the
Matplotlib Agg canvas.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass
import math
import os
from pathlib import Path
import tempfile
from typing import Callable, Iterable, Sequence

import numpy as np

from grim_dataset import RcsGrid


@dataclass(frozen=True)
class DatasetReference:
    """Stable recorder identity plus the best durable source for one GUI row."""

    dataset_id: str
    name: str
    path: str = ""


@dataclass(frozen=True)
class _Code:
    text: str


def _literal(value) -> str:
    """Render deterministic Python literals for resolved GUI parameters."""

    if isinstance(value, _Code):
        return value.text
    if isinstance(value, Path):
        return f"Path({_literal(str(value))})"
    if isinstance(value, np.generic):
        return _literal(value.item())
    if isinstance(value, np.ndarray):
        return _literal(value.tolist())
    if isinstance(value, float):
        if math.isnan(value):
            return "float('nan')"
        if math.isinf(value):
            return "float('inf')" if value > 0 else "float('-inf')"
        return repr(value)
    if isinstance(value, tuple):
        body = ", ".join(_literal(item) for item in value)
        if len(value) == 1:
            body += ","
        return f"({body})"
    if isinstance(value, list):
        return "[" + ", ".join(_literal(item) for item in value) + "]"
    if isinstance(value, dict):
        pairs = [f"{_literal(key)}: {_literal(item)}" for key, item in value.items()]
        return "{" + ", ".join(pairs) + "}"
    return repr(value)


def _call_text(callable_text: str, args=(), kwargs=None, *, indent: str = "") -> str:
    kwargs = kwargs or {}
    rendered = [_literal(value) for value in args]
    rendered.extend(f"{key}={_literal(value)}" for key, value in kwargs.items())
    if not rendered:
        return f"{callable_text}()"
    if len(rendered) == 1 and len(rendered[0]) < 72:
        return f"{callable_text}({rendered[0]})"
    continuation = indent + "    "
    return (
        f"{callable_text}(\n"
        + "".join(f"{continuation}{value},\n" for value in rendered)
        + f"{indent})"
    )


class PythonScriptRecorder:
    """Accumulate a readable, dependency-aware Python script.

    Dataset bindings use the immutable ``DATASET_ID_ROLE`` UUID from the GUI,
    never the editable display name.  A row is loaded lazily from its resolved
    path the first time it participates in a recorded operation.
    """

    _HEADER = f'''\
"""Generated by GRIM.  Dataset operations and plot output only."""

import os
from pathlib import Path
import sys

# Set GRIM_MODULE_DIR to the folder containing grim_dataset.py when replaying
# outside the source/install tree used to create this script.
_grim_module_override = os.environ.get("GRIM_MODULE_DIR")
if _grim_module_override:
    _grim_module_candidates = [Path(_grim_module_override).expanduser()]
else:
    _script_dir = Path(__file__).resolve().parent
    _grim_module_candidates = [
        Path({str(Path(__file__).resolve().parent)!r}),
        _script_dir,
        _script_dir / "GRIM_Revised_2",
    ]

GRIM_MODULE_DIR = None
for _candidate in _grim_module_candidates:
    _candidate = _candidate.resolve()
    if (_candidate / "grim_dataset.py").is_file():
        GRIM_MODULE_DIR = _candidate
        if str(_candidate) not in sys.path:
            sys.path.insert(0, str(_candidate))
        break

try:
    import numpy as np

    from grim_dataset import RcsGrid
    from grim_headless import load_dataset
    from grim_python import (
        coherent_divide,
        convert_extrusion,
        duplicate_dataset,
        join_datasets,
        medianize_azimuth,
        offset_db,
        plot_datasets,
        save_dataset_batch,
        shift_dataset,
        wedge_to_conic,
    )
except ModuleNotFoundError as exc:
    if exc.name in {{"grim_dataset", "grim_headless", "grim_python"}}:
        raise ModuleNotFoundError(
            "GRIM could not be imported. Install the GRIM package, place this "
            "script beside GRIM_Revised_2, or set GRIM_MODULE_DIR to the "
            "folder containing grim_dataset.py."
        ) from exc
    raise
'''

    def __init__(self, on_change: Callable[[str], None] | None = None) -> None:
        self._on_change = on_change
        self._lines: list[str] = []
        self._dataset_vars: dict[str, str] = {}
        self._next_dataset = 1
        self._next_plot = 1
        self._current_plot_var: str | None = None
        self._current_plot_signature: str | None = None
        self._notify()

    @property
    def script(self) -> str:
        body = "\n".join(self._lines)
        if body:
            body = "\n" + body.rstrip() + "\n"
        return self._HEADER + body

    def set_on_change(self, callback: Callable[[str], None] | None) -> None:
        self._on_change = callback
        self._notify()

    def _notify(self) -> None:
        if self._on_change is not None:
            self._on_change(self.script)

    def clear(self) -> None:
        self._lines.clear()
        self._dataset_vars.clear()
        self._next_dataset = 1
        self._next_plot = 1
        self._current_plot_var = None
        self._current_plot_signature = None
        self._notify()

    def _new_dataset_var(self, dataset_id: str) -> str:
        variable = f"dataset_{self._next_dataset}"
        self._next_dataset += 1
        self._dataset_vars[str(dataset_id)] = variable
        return variable

    def bind_loaded(self, reference: DatasetReference) -> str | None:
        existing = self._dataset_vars.get(reference.dataset_id)
        if existing is not None:
            return existing
        if not reference.path:
            return None
        variable = self._new_dataset_var(reference.dataset_id)
        resolved = str(Path(reference.path).expanduser().resolve())
        self._lines.extend(
            [
                f"# Load {reference.name}",
                f"{variable} = load_dataset(Path({_literal(resolved)}))",
                "",
            ]
        )
        self._notify()
        return variable

    def _ensure(self, reference: DatasetReference) -> str | None:
        return self._dataset_vars.get(reference.dataset_id) or self.bind_loaded(reference)

    def _skip_unbound(self, operation: str, references: Sequence[DatasetReference]) -> None:
        names = ", ".join(ref.name for ref in references if not ref.path)
        self._lines.extend(
            [
                f"# {operation} was not recorded: {names or 'an input dataset'} has no replayable source.",
                "# Save that dataset, clear this script, and repeat the operation to capture it.",
                "",
            ]
        )
        self._notify()

    def record_method(
        self,
        output: DatasetReference,
        source: DatasetReference,
        method: str,
        *,
        args=(),
        kwargs=None,
        comment: str = "",
    ) -> str | None:
        source_var = self._ensure(source)
        if source_var is None:
            self._skip_unbound(comment or method, [source])
            return None
        output_var = self._new_dataset_var(output.dataset_id)
        if comment:
            self._lines.append(f"# {comment}")
        call = _call_text(f"{source_var}.{method}", args, kwargs)
        self._lines.extend([f"{output_var} = {call}", ""])
        self._notify()
        return output_var

    def record_function(
        self,
        output: DatasetReference,
        function: str,
        sources: Sequence[DatasetReference],
        *,
        args=(),
        kwargs=None,
        comment: str = "",
    ) -> str | None:
        variables = [self._ensure(reference) for reference in sources]
        if any(variable is None for variable in variables):
            self._skip_unbound(comment or function, sources)
            return None
        output_var = self._new_dataset_var(output.dataset_id)
        if comment:
            self._lines.append(f"# {comment}")
        call_args = tuple(_Code(str(variable)) for variable in variables) + tuple(args)
        call = _call_text(function, call_args, kwargs)
        self._lines.extend([f"{output_var} = {call}", ""])
        self._notify()
        return output_var

    def record_multi_function(
        self,
        outputs: Sequence[DatasetReference],
        function: str,
        sources: Sequence[DatasetReference],
        *,
        args=(),
        kwargs=None,
        comment: str = "",
    ) -> tuple[str, ...]:
        variables = [self._ensure(reference) for reference in sources]
        if any(variable is None for variable in variables):
            self._skip_unbound(comment or function, sources)
            return ()
        output_vars = tuple(self._new_dataset_var(output.dataset_id) for output in outputs)
        if comment:
            self._lines.append(f"# {comment}")
        call_args = tuple(_Code(str(variable)) for variable in variables) + tuple(args)
        call = _call_text(function, call_args, kwargs)
        self._lines.extend([f"{', '.join(output_vars)} = {call}", ""])
        self._notify()
        return output_vars

    def record_expression(
        self,
        output: DatasetReference,
        sources: Sequence[DatasetReference],
        expression: Callable[[tuple[str, ...]], str],
        *,
        comment: str,
    ) -> str | None:
        variables = tuple(self._ensure(reference) for reference in sources)
        if any(variable is None for variable in variables):
            self._skip_unbound(comment, sources)
            return None
        output_var = self._new_dataset_var(output.dataset_id)
        self._lines.extend(
            [f"# {comment}", f"{output_var} = {expression(tuple(str(v) for v in variables))}", ""]
        )
        self._notify()
        return output_var

    def record_save(self, reference: DatasetReference, path: str) -> bool:
        variable = self._ensure(reference)
        if variable is None:
            self._skip_unbound("Save dataset", [reference])
            return False
        resolved = str(Path(path).expanduser().resolve())
        self._lines.extend(
            [
                f"# Save {reference.name}",
                f"{variable}.save(Path({_literal(resolved)}))",
                "",
            ]
        )
        self._notify()
        return True

    def record_save_batch(
        self,
        entries: Sequence[tuple[DatasetReference, str]],
    ) -> bool:
        """Emit one transactional save call while preserving GUI plan order."""

        if not entries:
            return False
        variables = [self._ensure(reference) for reference, _path in entries]
        if any(variable is None for variable in variables):
            self._skip_unbound(
                "Save dataset batch", [reference for reference, _path in entries]
            )
            return False
        self._lines.extend(
            ["# Transactionally save the dataset batch", "save_dataset_batch(["]
        )
        for variable, (_reference, path) in zip(variables, entries):
            resolved = str(Path(path).expanduser().resolve())
            self._lines.append(
                f"    ({variable}, Path({_literal(resolved)})),"
            )
        self._lines.extend(["])", ""])
        self._notify()
        return True

    def record_plot(
        self,
        datasets: Sequence[DatasetReference],
        *,
        names: Sequence[str],
        mode: str,
        parameters: dict[str, object],
    ) -> str | None:
        supported = {
            "azimuth_rect",
            "azimuth_polar",
            "frequency",
            "elevation_sweep",
        }
        mode_key = str(mode).strip().lower()
        if mode_key not in supported:
            self.record_unsupported_plot(
                mode_key,
                "the current headless recorder supports rectangular/polar "
                "azimuth, frequency, and elevation-sweep plots only",
            )
            return None
        variables = [self._ensure(reference) for reference in datasets]
        if any(variable is None for variable in variables):
            self._skip_unbound(f"Create {mode} plot", datasets)
            self._current_plot_var = None
            self._current_plot_signature = None
            return None
        signature = _literal(
            (
                tuple(
                    (reference.dataset_id, str(name))
                    for reference, name in zip(datasets, names)
                ),
                mode_key,
                parameters,
            )
        )
        if (
            self._current_plot_var is not None
            and signature == self._current_plot_signature
        ):
            return self._current_plot_var
        variable = f"plot_{self._next_plot}"
        self._next_plot += 1
        named = [
            (str(name), _Code(str(dataset_var)))
            for name, dataset_var in zip(names, variables)
        ]
        kwargs = {"mode": mode_key, **parameters}
        self._lines.append(f"# Create {mode_key.replace('_', ' ')} plot")
        call = _call_text("plot_datasets", (named,), kwargs)
        self._lines.extend([f"{variable} = {call}", ""])
        self._current_plot_var = variable
        self._current_plot_signature = signature
        self._notify()
        return variable

    def record_unsupported_plot(self, mode: str, reason: str) -> None:
        """Explain an omitted plot and prevent export from targeting stale code."""

        signature = _literal(("unsupported", str(mode), str(reason)))
        if self._current_plot_var is None and self._current_plot_signature == signature:
            return
        self._current_plot_var = None
        self._current_plot_signature = signature
        self._lines.extend(
            [
                f"# {str(mode).replace('_', ' ')} plot was not recorded: {reason}.",
                "# The plot shown in GRIM can still be exported manually.",
                "",
            ]
        )
        self._notify()

    def invalidate_current_plot(self) -> None:
        """Forget the export target without recording a presentation-only action."""

        self._current_plot_var = None
        self._current_plot_signature = None

    def record_plot_save(self, path: str, *, dpi: int = 200) -> bool:
        if self._current_plot_var is None:
            self._lines.extend(
                [
                    "# Plot export was not recorded: create a recorded plot first.",
                    "",
                ]
            )
            self._notify()
            return False
        resolved = str(Path(path).expanduser().resolve())
        self._lines.extend(
            [
                f"{self._current_plot_var}.savefig(",
                f"    Path({_literal(resolved)}),",
                f"    dpi={int(dpi)},",
                "    bbox_inches='tight',",
                ")",
                "",
            ]
        )
        self._notify()
        return True


def _copy_grid(dataset: RcsGrid, *, rcs, rcs_power, rcs_domain=None, units=None) -> RcsGrid:
    return RcsGrid(
        dataset.azimuths,
        dataset.elevations,
        dataset.frequencies,
        dataset.polarizations,
        rcs=rcs,
        rcs_power=rcs_power,
        rcs_phase=None if rcs is not None else dataset.rcs_phase,
        rcs_domain=rcs_domain or dataset.rcs_domain,
        units=dict(dataset.units or {}) if units is None else dict(units),
        extra={
            "phase_reference": dataset.extra["phase_reference"]
            for _ in (0,)
            if "phase_reference" in dataset.extra
        },
    )


def duplicate_dataset(dataset: RcsGrid) -> RcsGrid:
    """Return a detached copy with the same numerical samples and metadata."""

    return RcsGrid(
        dataset.azimuths.copy(),
        dataset.elevations.copy(),
        dataset.frequencies.copy(),
        dataset.polarizations.copy(),
        rcs_power=dataset.rcs_power.copy(),
        rcs_phase=dataset.rcs_phase.copy(),
        rcs_domain=dataset.rcs_domain,
        source_path=dataset.source_path,
        history=dataset.history,
        units=copy.deepcopy(dataset.units or {}),
        extra=copy.deepcopy(dataset.extra or {}),
    )


def join_datasets(*datasets: RcsGrid, tol: float = 1.0e-6) -> RcsGrid:
    """Join grids with the GUI's conflict and available-memory policies."""

    try:
        import psutil

        available = int(psutil.virtual_memory().available)
    except (ImportError, AttributeError, OSError):
        available = None
    maximum = int(available * 0.5) if available is not None else None
    return RcsGrid.join_many(
        *datasets,
        tol=float(tol),
        overlap="error",
        max_output_bytes=maximum,
    )


class DatasetBatchRollbackError(RuntimeError):
    """A batch publication failed and an earlier artifact was not restored."""


def _grim_output_path(path: str | os.PathLike[str]) -> str:
    value = os.fspath(path)
    return value if value.casefold().endswith(".grim") else value + ".grim"


def _replace_file(source: str, destination: str) -> None:
    """Small publication seam kept separate for deterministic rollback tests."""

    os.replace(source, destination)


def save_dataset_batch(
    entries: Sequence[tuple[RcsGrid, str | os.PathLike[str]]],
) -> tuple[Path, ...]:
    """Stage and transactionally publish an ordered batch of GRIM datasets."""

    normalized = [(dataset, _grim_output_path(path)) for dataset, path in entries]
    if not normalized:
        raise ValueError("save_dataset_batch needs at least one dataset and path")
    keys: set[str] = set()
    for _dataset, target in normalized:
        key = os.path.abspath(os.path.normpath(target)).casefold()
        if key in keys:
            raise ValueError(f"multiple datasets resolve to the same output: {target}")
        keys.add(key)

    staged: list[tuple[str, str]] = []
    backups: dict[str, str | None] = {}
    publication_complete = False
    try:
        for dataset, target in normalized:
            if not isinstance(dataset, RcsGrid):
                raise TypeError("save_dataset_batch entries must contain RcsGrid objects")
            absolute_target = os.path.abspath(target)
            directory = os.path.dirname(absolute_target) or os.curdir
            if os.path.lexists(absolute_target) and not os.path.isfile(absolute_target):
                raise OSError(
                    f"output target exists but is not a regular file: {absolute_target}"
                )
            fd, stage_path = tempfile.mkstemp(
                prefix=".grim-stage-",
                suffix=".staging.grim",
                dir=directory,
            )
            os.close(fd)
            try:
                dataset.save(stage_path)
            except Exception:
                try:
                    os.unlink(stage_path)
                except OSError:
                    pass
                raise
            staged.append((stage_path, absolute_target))

        for stage_path, target in staged:
            backup_path: str | None = None
            if os.path.lexists(target):
                directory = os.path.dirname(target) or os.curdir
                fd, backup_path = tempfile.mkstemp(
                    prefix=".grim-backup-",
                    suffix=".backup",
                    dir=directory,
                )
                os.close(fd)
                try:
                    _replace_file(target, backup_path)
                except BaseException:
                    try:
                        os.unlink(backup_path)
                    except OSError:
                        pass
                    raise
            backups[target] = backup_path
            _replace_file(stage_path, target)
        publication_complete = True
    except Exception as original_error:
        rollback_errors: list[str] = []
        for target in reversed(list(backups)):
            backup_path = backups[target]
            try:
                if backup_path and os.path.lexists(backup_path):
                    _replace_file(backup_path, target)
                    backups[target] = None
                elif backup_path is None and os.path.lexists(target):
                    os.unlink(target)
            except OSError as exc:
                rollback_errors.append(f"{target}: {exc}")
        if rollback_errors:
            raise DatasetBatchRollbackError(
                "Dataset publication failed and rollback could not restore every "
                "prior artifact. Retained .grim-backup file(s): "
                + "; ".join(rollback_errors)
            ) from original_error
        raise
    finally:
        for stage_path, _target in staged:
            if os.path.lexists(stage_path):
                try:
                    os.unlink(stage_path)
                except OSError:
                    pass

    if publication_complete:
        for backup_path in backups.values():
            if backup_path and os.path.lexists(backup_path):
                try:
                    os.unlink(backup_path)
                except OSError:
                    pass
    return tuple(Path(target).resolve() for _dataset, target in normalized)


def shift_dataset(
    dataset: RcsGrid,
    *,
    azimuth_degrees: float | None = None,
    elevation_degrees: float | None = None,
    phase_degrees: float | None = None,
) -> RcsGrid:
    """Apply the GUI Shift operation with explicit enabled values."""

    result = dataset
    if azimuth_degrees is not None:
        result = result.shift_azimuth(float(azimuth_degrees))
    if elevation_degrees is not None:
        result = result.shift_elevation(float(elevation_degrees))
    if phase_degrees is not None:
        phasor = np.exp(1j * np.deg2rad(float(phase_degrees)))
        result = _copy_grid(
            result,
            rcs=result.rcs * phasor,
            rcs_power=result.rcs_power,
            rcs_domain="complex_amplitude",
        )
    return result


def offset_db(dataset: RcsGrid, value_db: float) -> RcsGrid:
    """Shift all displayed RCS values by a constant number of decibels."""

    scale = 10.0 ** (float(value_db) / 10.0)
    rcs = dataset.rcs * (math.sqrt(scale) if dataset.rcs_domain == "complex_amplitude" else scale)
    return _copy_grid(
        dataset,
        rcs=rcs,
        rcs_power=dataset.rcs_power * scale,
        rcs_domain=dataset.rcs_domain,
    )


def coherent_divide(numerator: RcsGrid, denominator: RcsGrid) -> RcsGrid:
    """Complex element-wise division using the GUI's finite/nonzero policy."""

    numerator._assert_compatible(denominator, coherent=True)
    left = numerator.rcs
    right = denominator.rcs
    result_rcs = np.full(
        left.shape,
        np.nan + 1j * np.nan,
        dtype=np.result_type(left.dtype, right.dtype),
    )
    valid = np.isfinite(left) & np.isfinite(right) & (right != 0)
    np.divide(left, right, out=result_rcs, where=valid)
    units = dict(numerator.units or {})
    units["rcs_log_unit"] = "dB"
    units["rcs_linear_quantity"] = "power_ratio"
    return RcsGrid(
        numerator.azimuths,
        numerator.elevations,
        numerator.frequencies,
        numerator.polarizations,
        result_rcs,
        rcs_power=np.abs(result_rcs) ** 2,
        rcs_domain="complex_amplitude",
        units=units,
    )


def convert_extrusion(dataset: RcsGrid, *, to: str, length_m: float) -> RcsGrid:
    """Convert between sigma_3d/dBsm and sigma_2d/dBke for an extrusion."""

    destination = str(to).strip().lower()
    if destination not in {"dbke", "dbsm"}:
        raise ValueError("to must be 'dbke' or 'dbsm'")
    length = float(length_m)
    if not math.isfinite(length) or length <= 0.0:
        raise ValueError("length_m must be positive and finite")
    frequency_hz = np.asarray(dataset._frequency_value_to_hz(dataset.frequencies), dtype=float)
    c0 = 299_792_458.0
    if destination == "dbke":
        scale = c0 / (2.0 * length * length * frequency_hz)
        quantity = "sigma_2d"
    else:
        scale = 2.0 * length * length * frequency_hz / c0
        quantity = "sigma_3d"
    scale = np.where(np.isfinite(frequency_hz) & (frequency_hz > 0.0), scale, np.nan)
    scale_4d = scale.reshape(1, 1, -1, 1)
    power = dataset.rcs_power * scale_4d
    units = dict(dataset.units or {})
    units["rcs_log_unit"] = "dBke" if destination == "dbke" else "dBsm"
    units["rcs_linear_quantity"] = quantity
    if dataset.rcs_domain == "complex_amplitude":
        rcs = dataset.rcs * np.sqrt(np.maximum(scale_4d, 0.0))
        return RcsGrid(
            dataset.azimuths,
            dataset.elevations,
            dataset.frequencies,
            dataset.polarizations,
            rcs,
            rcs_power=power,
            rcs_domain=dataset.rcs_domain,
            units=units,
        )
    return RcsGrid(
        dataset.azimuths,
        dataset.elevations,
        dataset.frequencies,
        dataset.polarizations,
        rcs=None,
        rcs_power=power,
        rcs_phase=dataset.rcs_phase,
        rcs_domain=dataset.rcs_domain,
        units=units,
    )


def medianize_azimuth(dataset: RcsGrid, *, window_degrees: float, slide_degrees: float) -> RcsGrid:
    """Medianize linear power over sliding azimuth windows."""

    window = float(window_degrees)
    slide = float(slide_degrees)
    if window <= 0.0 or slide <= 0.0:
        raise ValueError("window_degrees and slide_degrees must be positive")
    azimuth = np.asarray(dataset.azimuths, dtype=float)
    if azimuth.size < 2:
        raise ValueError("medianize requires at least two azimuth samples")
    half = window * 0.5
    first = float(azimuth.min()) + half
    last = float(azimuth.max()) - half
    if last < first:
        centers = np.asarray([(float(azimuth.min()) + float(azimuth.max())) * 0.5])
    else:
        count = int(np.floor((last - first) / slide + 1e-9)) + 1
        centers = first + np.arange(count, dtype=float) * slide
    shape = (centers.size,) + dataset.rcs_power.shape[1:]
    power = np.empty(shape, dtype=dataset.rcs_power.dtype)
    for index, center in enumerate(centers):
        samples = np.flatnonzero(np.abs(azimuth - center) <= half)
        if samples.size == 0:
            samples = np.asarray([int(np.argmin(np.abs(azimuth - center)))])
        power[index] = np.nanmedian(dataset.rcs_power[samples], axis=0)
    return RcsGrid(
        centers,
        dataset.elevations,
        dataset.frequencies,
        dataset.polarizations,
        rcs=None,
        rcs_power=power,
        rcs_phase=np.full_like(power, np.nan),
        rcs_domain=dataset.rcs_domain,
        units=dict(dataset.units or {}),
    )


def wedge_to_conic(
    dataset: RcsGrid,
    *,
    mode: str = "regrid",
    assume_missing_cross_pol_zero: bool = False,
) -> RcsGrid:
    """Replay the GUI's physical wedge-to-normal-conic conversion."""

    mode_key = str(mode).strip().lower()
    if mode_key == "relabel":
        raise ValueError(
            "Wedge relabel is not physically representable as a rectangular "
            "RcsGrid; use mode='regrid'."
        )
    if mode_key != "regrid":
        raise ValueError("mode must be 'regrid'")
    return dataset.convert_wedge_to_conic(
        attest_wedge_axes=True,
        assume_missing_cross_pol_zero=assume_missing_cross_pol_zero,
    )


def _indices(axis, selected, *, text=False, tolerance=1.0e-6) -> list[int]:
    values = np.asarray(axis)
    result: list[int] = []
    for requested in selected:
        if text:
            matches = np.flatnonzero(values.astype(str) == str(requested))
        else:
            matches = np.flatnonzero(
                np.isclose(values.astype(float), float(requested), atol=tolerance, rtol=0.0)
            )
        if matches.size != 1:
            raise ValueError(f"Selected value {requested!r} is missing or ambiguous")
        result.append(int(matches[0]))
    return result


def _display_values(dataset: RcsGrid, values, *, frequency, phase: bool, scale: str):
    if phase:
        return np.rad2deg(np.angle(values))
    if str(scale).lower() == "linear":
        return dataset.rcs_to_linear(values)
    return dataset.rcs_to_display_db(values, frequency_value=frequency)


def _plot_selection_indices(
    dataset: RcsGrid,
    azimuths,
    elevations,
    frequencies,
    polarization,
):
    """Return exact requested indices, or ``None`` like the GUI skip policy."""

    try:
        return (
            _indices(dataset.azimuths, azimuths),
            _indices(dataset.elevations, elevations),
            _indices(dataset.frequencies, frequencies),
            _indices(dataset.polarizations, [polarization], text=True)[0],
        )
    except (TypeError, ValueError):
        return None


def plot_datasets(
    datasets: Sequence[tuple[str, RcsGrid]],
    *,
    mode: str,
    azimuths: Iterable[float],
    elevations: Iterable[float],
    frequencies: Iterable[float],
    polarization: str,
    phase: bool = False,
    scale: str = "dbsm",
    colormap: str = "viridis",
    show_grid: bool = True,
    show_legend: bool = True,
    polar_zero: str = "N",
    waterfall_style: str = "Surface",
    isar_options: dict[str, object] | None = None,
):
    """Create a Matplotlib Figure from resolved physical selector values.

    The implementation uses :class:`~matplotlib.backends.backend_agg.FigureCanvasAgg`
    directly and never imports pyplot or Qt.  Returned figures support ordinary
    ``figure.savefig(...)`` calls in generated scripts.
    """

    from matplotlib.backends.backend_agg import FigureCanvasAgg
    from matplotlib.figure import Figure

    selected = [(str(name), grid) for name, grid in datasets]
    if not selected:
        raise ValueError("plot_datasets needs at least one dataset")
    mode_key = str(mode).strip().lower()
    supported_modes = {
        "azimuth_rect",
        "azimuth_polar",
        "frequency",
        "elevation_sweep",
    }
    if mode_key not in supported_modes:
        raise ValueError(
            f"Unsupported headless plot mode {mode!r}; supported modes are "
            "azimuth_rect, azimuth_polar, frequency, and elevation_sweep"
        )
    az_values = [float(value) for value in azimuths]
    el_values = [float(value) for value in elevations]
    freq_values = [float(value) for value in frequencies]
    if not az_values or not el_values or not freq_values:
        raise ValueError("azimuths, elevations, and frequencies cannot be empty")
    compatible_count = 0

    figure = Figure(figsize=(10.0, 6.0), dpi=100, facecolor="white")
    FigureCanvasAgg(figure)
    if mode_key == "azimuth_polar":
        axes = figure.add_subplot(111, projection="polar")
        axes.set_theta_zero_location(str(polar_zero))
        axes.set_theta_direction(-1)
    elif mode_key == "compare":
        axes, residual_axes = figure.subplots(
            2, 1, sharex=True, gridspec_kw={"height_ratios": [3, 1]}
        )
    elif mode_key == "waterfall":
        axes = figure.add_subplot(111, projection="3d")
    else:
        axes = figure.add_subplot(111)

    if mode_key in {"azimuth_rect", "azimuth_polar"}:
        for name, dataset in selected:
            indices = _plot_selection_indices(
                dataset, az_values, el_values, freq_values, polarization
            )
            if indices is None:
                continue
            az_idx, el_idx, fr_idx, pol_idx = indices
            compatible_count += 1
            order = np.argsort(np.asarray(dataset.azimuths)[az_idx])
            x = np.asarray(dataset.azimuths)[az_idx][order]
            if mode_key == "azimuth_polar":
                x = np.deg2rad(x)
            for fi in fr_idx:
                for ei in el_idx:
                    raw = (
                        dataset.rcs[np.ix_(az_idx, [ei], [fi], [pol_idx])][:, 0, 0, 0]
                        if phase
                        else dataset.rcs_power[np.ix_(az_idx, [ei], [fi], [pol_idx])][:, 0, 0, 0]
                    )
                    y = _display_values(
                        dataset,
                        raw,
                        frequency=float(dataset.frequencies[fi]),
                        phase=phase,
                        scale=scale,
                    )[order]
                    axes.plot(
                        x,
                        y,
                        label=(
                            f"{name} | {polarization}, {float(dataset.frequencies[fi]):g} "
                            f"{dataset.units.get('frequency', 'GHz')}, El {float(dataset.elevations[ei]):g}°"
                        ),
                    )
        if mode_key == "azimuth_rect":
            axes.set_xlabel("Azimuth (deg)")
        axes.set_ylabel("Phase (deg)" if phase else ("RCS (Linear)" if scale == "linear" else "RCS (dB)"))

    elif mode_key == "frequency":
        for name, dataset in selected:
            indices = _plot_selection_indices(
                dataset, az_values, el_values, freq_values, polarization
            )
            if indices is None:
                continue
            az_idx, el_idx, fr_idx, pol_idx = indices
            compatible_count += 1
            x = np.asarray(dataset.frequencies)[fr_idx]
            order = np.argsort(x)
            for ei in el_idx:
                if phase:
                    block = dataset.rcs[np.ix_(az_idx, [ei], fr_idx, [pol_idx])][:, 0, :, 0]
                    y = np.nanmedian(np.rad2deg(np.angle(block)), axis=0)
                else:
                    block = dataset.rcs_power[np.ix_(az_idx, [ei], fr_idx, [pol_idx])][:, 0, :, 0]
                    power = np.nanmedian(block, axis=0)
                    y = _display_values(dataset, power, frequency=x, phase=False, scale=scale)
                axes.plot(x[order], np.asarray(y)[order], label=f"{name} | El {dataset.elevations[ei]:g}°")
        axes.set_xlabel(f"Frequency ({selected[0][1].units.get('frequency', 'GHz')})")
        axes.set_ylabel("Phase P50 (deg)" if phase else ("RCS P50 (Linear)" if scale == "linear" else "RCS P50 (dB)"))

    elif mode_key == "elevation_sweep":
        for name, dataset in selected:
            indices = _plot_selection_indices(
                dataset, az_values, el_values, freq_values, polarization
            )
            if indices is None:
                continue
            az_idx, el_idx, fr_idx, pol_idx = indices
            compatible_count += 1
            x = np.asarray(dataset.elevations)[el_idx]
            order = np.argsort(x)
            for fi in fr_idx:
                if phase:
                    block = dataset.rcs[np.ix_(az_idx, el_idx, [fi], [pol_idx])][:, :, 0, 0]
                    y = np.nanmedian(np.rad2deg(np.angle(block)), axis=0) if len(az_idx) > 1 else np.rad2deg(np.angle(block[0]))
                else:
                    block = dataset.rcs_power[np.ix_(az_idx, el_idx, [fi], [pol_idx])][:, :, 0, 0]
                    power = np.nanmedian(block, axis=0) if len(az_idx) > 1 else block[0]
                    y = _display_values(dataset, power, frequency=dataset.frequencies[fi], phase=False, scale=scale)
                axes.plot(x[order], np.asarray(y)[order], label=f"{name} | {dataset.frequencies[fi]:g}")
        axes.set_xlabel("Elevation (deg)")
        axes.set_ylabel("Phase (deg)" if phase else ("RCS (Linear)" if scale == "linear" else "RCS (dB)"))

    elif mode_key == "compare":
        if len(selected) != 2:
            raise ValueError("compare requires exactly two datasets")
        varying = "azimuth" if len(az_values) > 1 else "elevation" if len(el_values) > 1 else "frequency"
        series_values = []
        for name, dataset in selected:
            az_idx = _indices(dataset.azimuths, az_values)
            el_idx = _indices(dataset.elevations, el_values)
            fr_idx = _indices(dataset.frequencies, freq_values)
            pol_idx = _indices(dataset.polarizations, [polarization], text=True)[0]
            if varying == "azimuth":
                x = np.asarray(dataset.azimuths)[az_idx]
                raw = (dataset.rcs if phase else dataset.rcs_power)[np.ix_(az_idx, [el_idx[0]], [fr_idx[0]], [pol_idx])][:, 0, 0, 0]
                frequency = dataset.frequencies[fr_idx[0]]
            elif varying == "elevation":
                x = np.asarray(dataset.elevations)[el_idx]
                raw = (dataset.rcs if phase else dataset.rcs_power)[np.ix_([az_idx[0]], el_idx, [fr_idx[0]], [pol_idx])][0, :, 0, 0]
                frequency = dataset.frequencies[fr_idx[0]]
            else:
                x = np.asarray(dataset.frequencies)[fr_idx]
                raw = (dataset.rcs if phase else dataset.rcs_power)[np.ix_([az_idx[0]], [el_idx[0]], fr_idx, [pol_idx])][0, 0, :, 0]
                frequency = x
            y = _display_values(dataset, raw, frequency=frequency, phase=phase, scale=scale)
            order = np.argsort(x)
            x, y = np.asarray(x)[order], np.asarray(y)[order]
            axes.plot(x, y, label=name)
            series_values.append((x, y))
        common, left_idx, right_idx = np.intersect1d(
            np.round(series_values[0][0], 8),
            np.round(series_values[1][0], 8),
            return_indices=True,
        )
        if common.size:
            residual_axes.plot(common, series_values[0][1][left_idx] - series_values[1][1][right_idx])
        residual_axes.axhline(0.0, color="gray", linestyle="--")
        residual_axes.set_xlabel(varying.title())
        residual_axes.set_ylabel("Residual")
        axes.set_ylabel("Phase (deg)" if phase else ("RCS (Linear)" if scale == "linear" else "RCS (dB)"))

    elif mode_key == "waterfall":
        for name, dataset in selected:
            az_idx = _indices(dataset.azimuths, az_values)
            el_idx = _indices(dataset.elevations, el_values)
            fr_idx = _indices(dataset.frequencies, freq_values)
            pol_idx = _indices(dataset.polarizations, [polarization], text=True)[0]
            az_axis = np.asarray(dataset.azimuths)[az_idx]
            fr_axis = np.asarray(dataset.frequencies)[fr_idx]
            x_mesh, y_mesh = np.meshgrid(az_axis, fr_axis, indexing="ij")
            for ei in el_idx:
                raw = (dataset.rcs if phase else dataset.rcs_power)[np.ix_(az_idx, [ei], fr_idx, [pol_idx])][:, 0, :, 0]
                z = _display_values(dataset, raw, frequency=fr_axis[None, :], phase=phase, scale=scale)
                if str(waterfall_style).lower().startswith("wire"):
                    axes.plot_wireframe(x_mesh, y_mesh, z, label=name)
                else:
                    axes.plot_surface(x_mesh, y_mesh, z, cmap=colormap, alpha=0.85)
        axes.set_xlabel("Azimuth (deg)")
        axes.set_ylabel(f"Frequency ({selected[0][1].units.get('frequency', 'GHz')})")
        axes.set_zlabel("Phase (deg)" if phase else ("RCS (Linear)" if scale == "linear" else "RCS (dB)"))

    elif mode_key == "az_vs_range":
        dataset = selected[0][1]
        name = selected[0][0]
        az_idx = _indices(dataset.azimuths, az_values)
        fr_idx = _indices(dataset.frequencies, freq_values)
        el_idx = _indices(dataset.elevations, [el_values[0]])[0]
        pol_idx = _indices(dataset.polarizations, [polarization], text=True)[0]
        freq = np.asarray(dataset._frequency_value_to_hz(dataset.frequencies[fr_idx]), dtype=float)
        order_f = np.argsort(freq)
        freq = freq[order_f]
        complex_data = dataset.rcs[np.ix_(az_idx, [el_idx], fr_idx, [pol_idx])][:, 0, :, 0][:, order_f]
        window = np.hanning(freq.size)
        image = np.fft.fftshift(np.fft.ifft(complex_data * window[None, :], axis=1), axes=1)
        distance = np.fft.fftshift(np.fft.fftfreq(freq.size, d=float(np.mean(np.diff(freq))))) * 299_792_458.0 / 2.0
        magnitude = np.abs(image)
        display = magnitude if scale == "linear" else 20.0 * np.log10(np.maximum(magnitude, 1.0e-15))
        axes.pcolormesh(np.asarray(dataset.azimuths)[az_idx], distance, display.T, shading="auto", cmap=colormap)
        axes.set_title(name)
        axes.set_xlabel("Azimuth (deg)")
        axes.set_ylabel("Down-Range (m)")

    elif mode_key == "isar_image":
        from plot_modes.isar_mode import form_isar

        dataset = selected[0][1]
        options = dict(isar_options or {})
        az_idx = _indices(dataset.azimuths, az_values)
        fr_idx = _indices(dataset.frequencies, freq_values)
        el_idx = _indices(dataset.elevations, [el_values[0]])[0]
        pol_idx = _indices(dataset.polarizations, [polarization], text=True)[0]
        bands, _elapsed = form_isar(
            dataset,
            azimuth_indices=az_idx,
            frequency_indices=fr_idx,
            elevation_index=el_idx,
            polarization_index=pol_idx,
            **options,
        )
        figure.clear()
        axes_values = figure.subplots(1, len(bands), squeeze=False)[0]
        for axis, band in zip(axes_values, bands):
            magnitude = np.asarray(band["magnitude"])
            display = magnitude if scale == "linear" else 20.0 * np.log10(np.maximum(magnitude, 1.0e-15))
            axis.imshow(
                display.T,
                extent=[band["x_range"][0], band["x_range"][-1], band["y_range"][0], band["y_range"][-1]],
                origin="lower",
                aspect="auto",
                cmap=colormap,
            )
            axis.set_xlabel("Cross-Range")
            axis.set_ylabel("Down-Range")
        axes = axes_values[0]
    else:
        raise ValueError(f"Unsupported plot mode: {mode!r}")

    if compatible_count == 0:
        figure.clear()
        raise ValueError(
            "None of the selected datasets contains every requested plot axis value"
        )

    for axis in figure.axes:
        axis.grid(bool(show_grid))
        handles, labels = axis.get_legend_handles_labels()
        if show_legend and handles:
            axis.legend()
    figure.tight_layout()
    return figure


__all__ = [
    "DatasetBatchRollbackError",
    "DatasetReference",
    "PythonScriptRecorder",
    "coherent_divide",
    "convert_extrusion",
    "duplicate_dataset",
    "join_datasets",
    "medianize_azimuth",
    "offset_db",
    "plot_datasets",
    "save_dataset_batch",
    "shift_dataset",
    "wedge_to_conic",
]
